import './style.css';
import './readability.css';
import { PARTS, SHOTS, STATUS, createFindings, summarize, validateFinding, captureProgress, makeReport } from './domain.js';
import { CarViewer } from './car.js';
import { readState, writeState, preparePhoto } from './storage.js';

const icons={cube:'M12 3 3 8v9l9 5 9-5V8l-9-5Z M3 8l9 5 9-5 M12 13v9',camera:'M4 6h4l2-3h4l2 3h4v14H4V6Z M16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',grid:'M3 3h7v7H3V3Z M14 3h7v7h-7V3Z M3 14h7v7H3v-7Z M14 14h7v7h-7v-7Z',check:'m5 12 4 4L19 6',arrow:'M5 12h14 m-5-5 5 5-5 5',chevron:'m9 5 7 7-7 7',download:'M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5',rotate:'M20 7v5h-5 M20 12a8 8 0 1 0-2 6',layers:'m12 3 10 6-10 6L2 9l10-6Z M2 13l10 6 10-6 M2 17l10 6 10-6',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',info:'M12 11v6 M12 7v1 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',close:'m6 6 12 12 M6 18 18 6',edit:'m16 3 5 5-12 12-6 1 1-6L16 3Z M14 5l5 5',file:'M14 2H4v20h16V8l-6-6Z M14 2v6h6 M8 13h8 M8 17h6',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z m-4 10 3 3 5-6',phone:'M7 2h10v20H7V2Z M10 18h4',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 1v3 M12 20v3 M1 12h3 M20 12h3 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2',monitor:'M2 3h20v14H2V3Z M12 17v5 M7 22h10',target:'M12 2v4 M12 18v4 M2 12h4 M18 12h4 M19 12a7 7 0 1 1-14 0 7 7 0 0 1 14 0',refresh:'M21 3v6h-6 M3 21v-6h6 M4 9a8 8 0 0 1 14-5l3 5 M3 15l3 5a8 8 0 0 0 14-5',lock:'M5 10h14v12H5V10Z M8 10V6a4 4 0 0 1 8 0v4',help:'M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3 M12 17v1 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.cube}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={findings:createFindings(),photos:{},mode:'demo'};
let selected='left_front_door',activeShot='ring-2',page='report',customer=false,filter='all',thumbs={},viewer,toastTimer,saveQueue=Promise.resolve();
try{const saved=await readState();if(saved?.version===1){state=saved;for(const p of PARTS)state.findings[p.id]=validateFinding(p.id,state.findings[p.id]);}}catch{state={findings:createFindings(),photos:{},mode:'demo'};}
const $=s=>document.querySelector(s);
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4300);}
async function persist(){
  const snapshot=structuredClone({...state,version:1});
  const op=saveQueue.catch(()=>{}).then(()=>writeState(snapshot));saveQueue=op;
  try{await op;$('#storage-status').textContent='Bu cihazda kayıtlı';return true;}catch{$('#storage-status').textContent='Kayıt başarısız';toast('Tarayıcıya kaydedilemedi. Alanı kontrol edin; veriler bu oturumda açık kalır.');return false;}
}
function badge(status){const s=STATUS[status];return `<span class="status-chip" style="--status:${s.dot}"><i></i>${s.label}</span>`;}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

$('#app').innerHTML=`
  <aside class="rail">
    <a class="brand" href="#" aria-label="OTOTR 3D ekspertiz ana ekranı"><span>OTO<span class="brand-red">TR</span><b>®</b></span><small>EKSPERTİZ TEKNOLOJİLERİ</small></a>
    <div class="workspace-label">ÇALIŞMA ALANI</div>
    <nav class="rail-nav" aria-label="Ana gezinme">
      <button class="nav-item active" data-page="report">${icon('cube')}<span>3D Ekspertiz</span><i></i></button>
      <button class="nav-item" data-page="capture">${icon('camera')}<span>Fotoğraf çekimi</span><small>24</small></button>
      <button class="nav-item" data-page="plan">${icon('grid')}<span>Sistem & kurulum</span></button>
    </nav>
    <div class="rail-note">${icon('shield')}<h4>Kanıtıyla anlatın.</h4><p>Her parça, kendi bulgusu ve fotoğrafıyla aynı yerde.</p><span>OTOTR VISION <b>01</b></span></div>
    <div class="rail-bottom"><span class="avatar">OT</span><div><strong>Ototr örnek şube</strong><small>Yerel çalışma alanı</small></div></div>
  </aside>
  <div class="app-main">
    <header class="topbar"><div class="breadcrumb">Çalışma alanı ${icon('chevron')} <strong id="crumb">3D Ekspertiz</strong></div><div class="topbar-right"><a class="real-alternative-link" href="./real-360.html">${icon('camera')} Gerçek fotoğraflı alternatif ${icon('arrow')}</a><span class="demo-pill"><i></i> ETKİLEŞİMLİ DEMO</span></div></header>
    <main>
      <section class="page-heading"><div><div class="eyebrow">OTOTR VISION</div><h1 id="page-title">Aracın her açısı. <span>Raporun her detayı.</span></h1><p id="page-description">Aracı döndürün, bir parçaya dokunun ve ekspertiz bulgusunu inceleyin.</p></div><button class="button primary" id="customer-toggle">${icon('eye')} Müşteri görünümü</button></section>
      <div id="customer-banner" class="customer-banner" hidden>${icon('eye')} Müşteri ekranı önizlemesi · Örnek veridir; teknik onaylı rapor değildir.<button id="exit-customer">Düzenlemeye dön ${icon('arrow')}</button></div>
      <section id="report-page" class="page">
        <div class="vehicle-bar"><div class="vehicle-symbol">${icon('cube')}</div><div class="vehicle-name"><strong>OTOTR Sedan</strong><span>Temsili araç modeli <i>•</i> Dış kaporta incelemesi</span></div><div class="vehicle-facts"><div><small>PARÇA HARİTASI</small><strong>25 <span>parça</span></strong></div><div><small>KAYITLI BULGU</small><strong id="finding-count">4 <span>parça</span></strong></div><div><small>FOTOĞRAF PLANI</small><strong>24 <span>poz</span></strong></div></div><span class="thin-badge">ÖRNEK RAPOR</span></div>
        <div class="inspection-layout">
          <section class="viewer-card" aria-label="Etkileşimli kaporta haritası">
            <div class="viewer-toolbar"><div class="segmented"><button id="color-view" class="active" aria-pressed="true">${icon('layers')} Kaporta durumu</button><button id="plain-view" aria-pressed="false">Doğal görünüm</button></div><button id="reset-view" class="icon-button" title="Açıyı sıfırla" aria-label="Açıyı sıfırla">${icon('rotate')}</button></div>
            <div id="car-host"><div class="viewer-loading">3D araç hazırlanıyor…</div></div>
            <div class="model-origin">${icon('cube')} TEMSİLİ 3D MODEL</div>
            <div class="orientation"><span>ÖN</span><div>↖</div></div>
            <div class="floating-tools"><button id="rotate-toggle" class="icon-button" aria-label="Otomatik döndür" title="Otomatik döndür" aria-pressed="false">${icon('rotate')}</button><button id="explode-toggle" class="icon-button" aria-label="Parçaları ayır" title="Parçaları ayır" aria-pressed="false">${icon('layers')}</button><span></span><button id="zoom-in" class="icon-button" aria-label="Yakınlaştır">${icon('plus')}</button><button id="zoom-out" class="icon-button" aria-label="Uzaklaştır">${icon('minus')}</button></div>
            <div class="viewer-footer"><span>${icon('target')} Sürükle: döndür <b>·</b> Dokun: parçayı incele</span><button id="top-view">Üstten bak ${icon('arrow')}</button></div>
            <div class="legend" id="legend"></div>
          </section>
          <aside class="detail-card" id="part-detail"></aside>
        </div>
        <section class="photo-section"><div class="section-heading"><div><h2>Aracın etrafında bir tur</h2><span>Açıları seçerek modeli aynı yönden inceleyin.</span></div><button class="text-button" data-page="capture">Çekim planını aç ${icon('arrow')}</button></div><div class="filmstrip" id="filmstrip"></div><div class="photo-origin-note">${icon('info')} Örnek kareler aynı 3D modelden üretilen renderlardır; gerçek fotoğraf veya fotogrametri sonucu değildir.</div></section>
        <section class="parts-section"><div class="section-heading"><div><h2>Parça dökümü <span class="count">25</span></h2><span>Sol ve sağ, sürücünün ileri bakış yönüne göredir.</span></div><label class="filter-label">Göster <select id="part-filter"><option value="all">Tüm parçalar</option><option value="findings">Yalnızca bulgular</option><option value="unchecked">İncelenmeyenler</option></select></label></div><div id="parts-grid" class="parts-grid"></div><div class="scope-note">Bu harita dış yüzeyleri gösterir. Şasi, podye, direk içleri, taban ve gizli bölgeler için ayrıca fiziksel inceleme ve kanıt gerekir.</div></section>
      </section>
      <section id="capture-page" class="page" hidden>
        <div class="capture-summary"><div class="capture-progress-ring" id="capture-ring"><strong id="capture-total">0</strong><small>/ 24 FOTOĞRAF</small></div><div><h2>Her araçta aynı çekim standardı.</h2><p>12 çevre açısı + 4 üst açı + 8 parça detayı. Gerçek fotoğrafları sırayla ekleyin.</p><div id="capture-status" class="capture-status"></div></div><button class="button" id="new-capture">${icon('plus')} Boş çekim başlat</button></div>
        <div class="capture-layout"><section class="capture-guide"><div class="guide-header"><span class="eyebrow" id="shot-group"></span><span id="shot-number" class="thin-badge"></span></div><h2 id="shot-name"></h2><div class="shot-preview"><img id="shot-preview" alt="Seçili çekim açısı için temsili kılavuz"/><div class="frame-corner tl"></div><div class="frame-corner tr"></div><div class="frame-corner bl"></div><div class="frame-corner br"></div><span id="shot-origin" class="preview-label"></span></div><div class="guide-facts"><div>${icon('rotate')}<span>Yatay açı<strong id="shot-angle"></strong></span></div><div>${icon('camera')}<span>Kamera yüksekliği<strong id="shot-height"></strong></span></div></div><p id="shot-hint"></p><label class="upload-button button primary" for="photo-upload">${icon('camera')} Fotoğraf çek / yükle</label><input id="photo-upload" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden/><div class="upload-note">JPG, PNG, WebP · En fazla 20 MB · Kısa kenar en az 720 px</div><div class="guide-nav"><button class="button" id="prev-shot">Önceki poz</button><button class="button" id="next-shot">Sonraki poz ${icon('arrow')}</button></div><button id="remove-photo" class="text-button danger" hidden>Bu pozdaki fotoğrafı kaldır</button></section><section class="shot-list-card"><div class="section-heading"><h2>Çekim listesi</h2><span class="thin-badge">24 ZORUNLU POZ</span></div><div id="shot-list"></div></section></div>
        <div class="capture-tip">${icon('info')}<div><strong>Yükleme, teknik onay anlamına gelmez.</strong><p>Bu örnek dosya türü, boyut, çözünürlük ve birebir tekrar kontrolü yapar. Açı doğruluğu, netlik ve kaporta bulgusu uzman tarafından değerlendirilir. Fotoğraflar bu tarayıcıda saklanır.</p></div></div>
      </section>
      <section id="plan-page" class="page" hidden></section>
      <footer class="page-footer"><span>${icon('lock')} <span id="storage-status">Bu cihazda çalışır</span> <i>·</i> Veriler sunucuya gönderilmez.</span><button id="export-model">${icon('cube')} 3D modeli indir</button><button id="export-report">${icon('download')} Rapor taslağı indir</button></footer>
    </main>
  </div>
  <dialog id="edit-dialog" class="edit-dialog"><form id="edit-form"><div class="dialog-heading"><div><span class="eyebrow">UZMAN KAYDI</span><h2 id="edit-title"></h2></div><button type="button" class="icon-button" data-close="edit-dialog" aria-label="Kapat">${icon('close')}</button></div><label>Parça durumu<select id="edit-status">${Object.entries(STATUS).map(([id,s])=>`<option value="${id}">${s.label}</option>`).join('')}</select></label><label id="measurement-field">Boya ölçümleri (µm)<input id="edit-measurements" placeholder="Örn. 112, 118, 115" maxlength="150"/><small>Ölçüm tek başına boya veya değişim kararı vermez.</small></label><label>Uzman açıklaması<textarea id="edit-note" rows="5" maxlength="2000"></textarea></label><p id="edit-error" role="alert"></p><div class="dialog-actions"><button type="button" class="button" data-close="edit-dialog">Vazgeç</button><button class="button primary" type="submit">${icon('check')} Kaydı güncelle</button></div></form></dialog>
  <dialog id="photo-dialog" class="photo-dialog"><div class="dialog-heading"><h2 id="photo-title"></h2><button class="icon-button" data-close="photo-dialog" aria-label="Kapat">${icon('close')}</button></div><img id="large-photo" alt=""/><p id="large-photo-caption"></p></dialog>
  <dialog id="new-dialog" class="edit-dialog"><div class="dialog-heading"><h2>Yeni çekim alanı</h2><button class="icon-button" data-close="new-dialog" aria-label="Kapat">${icon('close')}</button></div><p>Yeni çalışma, mevcut yerel kaydın yerini alır. Önce rapor taslağını indirebilirsiniz. Tüm parçalar “İncelenmedi” durumuyla açılır.</p><div class="dialog-actions"><button class="button" data-close="new-dialog">Vazgeç</button><button class="button primary" id="confirm-new">Boş çekimi aç</button></div></dialog>
  <div id="toast" role="status" aria-live="polite"></div>`;

function renderSummary(){
  const summary=summarize(state.findings),count=summary.filter(s=>!['original','unchecked'].includes(s.status)).reduce((a,s)=>a+s.count,0);
  $('#finding-count').innerHTML=`${count} <span>parça</span>`;
  $('#legend').innerHTML=summary.map(s=>`<span><i style="background:${s.dot}"></i>${s.label}<b>${s.count}</b></span>`).join('');
}
function selectPart(id,focus=false){selected=id;viewer?.update(state.findings,selected);if(focus)viewer?.framePart(id);renderPart();renderParts();}
function renderPart(){
  const part=PARTS.find(p=>p.id===selected),finding=state.findings[selected],s=STATUS[finding.status];
  const measurements=finding.measurements?finding.measurements.split(', '):[];
  const evidence=SHOTS.filter(shot=>shot.parts.includes(selected)&&state.photos[shot.id]);
  const fallback=SHOTS.find(shot=>shot.parts.includes(selected))||SHOTS[2];
  $('#part-detail').innerHTML=`<div class="detail-kicker"><span>SEÇİLİ PARÇA</span><span>${String(PARTS.indexOf(part)+1).padStart(2,'0')} / 25</span></div><div class="detail-title"><h2>${part.name}</h2>${badge(finding.status)}</div><p class="part-group">${part.group} <span>·</span> ${part.material==='metal'?'Metal yüzey':part.material==='glass'?'Cam yüzey':'Plastik / kompozit'}</p><div class="detail-rule"></div><div class="detail-subtitle">${icon('target')} Boya kalınlığı ${state.mode==='demo'?'<span>ÖRNEK ÖLÇÜM</span>':''}</div><div class="measurement-grid">${measurements.length?measurements.map((v,i)=>`<div><small>Nokta ${i+1}</small><strong>${esc(v)}<span>µm</span></strong></div>`).join(''):`<div class="no-measurement">${part.material==='metal'?'Ölçüm girilmedi.':'Bu yüzeyde Fe/NFe ölçümü uygulanmaz.'}</div>`}</div><div class="expert-note"><span>UZMAN NOTU</span><p>${esc(finding.note||s.description)}</p></div><div class="evidence-heading"><h3>İlgili görseller</h3><span>${evidence.length}</span></div><div class="evidence-photos">${(evidence.length?evidence:[fallback]).slice(0,2).map(shot=>`<button class="evidence-photo" data-photo="${shot.id}"><img src="${state.photos[shot.id]?.url||thumbs[shot.id]||''}" alt="${esc(shot.name)}"/><span>${state.photos[shot.id]?.kind==='photo'?'Yüklenen fotoğraf':'Temsili render'} ${icon('plus')}</span></button>`).join('')}</div><button class="button detail-edit" id="edit-part" ${customer?'hidden':''}>${icon('edit')} Bulguyu düzenle</button><div class="detail-disclaimer">${icon('info')} ${state.mode==='demo'?'Bulgular ve ölçümler gösterim amaçlıdır.':'Yerel taslak; teknik onaylı rapor değildir.'}</div>`;
  $('#edit-part')?.addEventListener('click',()=>{if(customer)return;$('#edit-title').textContent=part.name;$('#edit-status').value=finding.status;$('#edit-measurements').value=finding.measurements;$('#edit-note').value=finding.note;$('#measurement-field').hidden=part.material!=='metal';$('#edit-error').textContent='';$('#edit-dialog').showModal();});
  $('#part-detail').querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>showPhoto(b.dataset.photo)));
}
function renderParts(){
  const parts=PARTS.filter(p=>filter==='all'||(filter==='unchecked'?state.findings[p.id].status==='unchecked':!['original','unchecked'].includes(state.findings[p.id].status)));
  $('#parts-grid').innerHTML=parts.length?parts.map(p=>`<button class="part-row ${p.id===selected?'selected':''}" data-part="${p.id}" aria-pressed="${p.id===selected}"><span>${p.name}</span>${badge(state.findings[p.id].status)}${icon('chevron')}</button>`).join(''):'<p class="empty-state">Bu filtreye uygun parça yok.</p>';
  $('#parts-grid').querySelectorAll('[data-part]').forEach(b=>b.addEventListener('click',()=>selectPart(b.dataset.part,true)));
}
const filmIds=['ring-1','ring-3','ring-5','ring-6','ring-7','ring-9','ring-11','high-0'];
function renderFilmstrip(){
  $('#filmstrip').innerHTML=filmIds.map(id=>{const shot=SHOTS.find(s=>s.id===id),photo=state.photos[id];return `<button class="film-card ${activeShot===id?'selected':''}" data-angle="${id}"><div><img src="${photo?.url||thumbs[id]||''}" alt="${shot.name}" loading="lazy"/><span>${photo?.kind==='photo'?'FOTOĞRAF':'RENDER'}</span></div><strong>${shot.name}</strong><small>${shot.elevation>20?'Üst açı':shot.angle+'° görüş'}</small></button>`;}).join('');
  $('#filmstrip').querySelectorAll('[data-angle]').forEach(b=>b.addEventListener('click',()=>{activeShot=b.dataset.angle;const shot=SHOTS.find(s=>s.id===activeShot);viewer?.view(shot.angle,shot.elevation||18);renderFilmstrip();}));
}
function showPhoto(id){const shot=SHOTS.find(s=>s.id===id),photo=state.photos[id];$('#photo-title').textContent=shot.name;$('#large-photo').src=photo?.url||thumbs[id]||'';$('#large-photo').alt=shot.name;$('#large-photo-caption').textContent=photo?.kind==='photo'?'Yerel yüklenen fotoğraf · Açı ve bulgu doğruluğu uzman kontrolü gerektirir.':'Temsili 3D render. Gerçek fotoğraf değildir ve bir ekspertiz bulgusuna kanıt oluşturmaz.';$('#photo-dialog').showModal();}
function renderCapture(){
  const progress=captureProgress(state.photos),shot=SHOTS.find(s=>s.id===activeShot),photo=state.photos[activeShot];
  $('#capture-total').textContent=progress.real;$('#capture-ring').style.setProperty('--progress',progress.percent+'%');
  $('#capture-status').innerHTML=`<span>${progress.real} gerçek fotoğraf yüklendi</span><span>${progress.examples} temsili örnek</span><span>${24-progress.real} poz eksik</span>`;
  $('#shot-group').textContent=shot.group;$('#shot-number').textContent=`POZ ${String(SHOTS.indexOf(shot)+1).padStart(2,'0')} / 24`;
  $('#shot-name').textContent=shot.name;$('#shot-preview').src=photo?.url||thumbs[shot.id]||'';$('#shot-origin').textContent=photo?.kind==='photo'?'Yüklenen fotoğraf · uzman kontrolü bekliyor':'Temsili çekim kılavuzu · 3D render';$('#shot-angle').textContent=shot.angle+'°';$('#shot-height').textContent=shot.height;$('#shot-hint').textContent=shot.hint;
  $('#remove-photo').hidden=photo?.kind!=='photo';$('#prev-shot').disabled=SHOTS.indexOf(shot)===0;$('#next-shot').disabled=SHOTS.indexOf(shot)===SHOTS.length-1;
  $('#shot-list').innerHTML=['Çevre turu','Üst açılar','Parça detayları'].map(group=>`<div class="shot-group-title">${group}<span>${SHOTS.filter(s=>s.group===group&&state.photos[s.id]?.kind==='photo').length} / ${SHOTS.filter(s=>s.group===group).length}</span></div><div class="shot-tiles">${SHOTS.filter(s=>s.group===group).map(s=>`<button class="shot-tile ${s.id===activeShot?'active':''} ${state.photos[s.id]?.kind==='photo'?'complete':''}" data-shot="${s.id}"><span>${state.photos[s.id]?.kind==='photo'?icon('check'):String(SHOTS.indexOf(s)+1).padStart(2,'0')}</span><strong>${s.name}</strong><small>${state.photos[s.id]?.kind==='photo'?'Yüklendi':s.angle+'°'}</small></button>`).join('')}</div>`).join('');
  $('#shot-list').querySelectorAll('[data-shot]').forEach(b=>b.addEventListener('click',()=>{activeShot=b.dataset.shot;renderCapture();}));
}

function showPage(next){
  page=next;for(const id of ['report','capture','plan'])$(`#${id}-page`).hidden=id!==next;
  document.querySelectorAll('.rail-nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===next));
  const text={report:['3D Ekspertiz','Aracın her açısı. <span>Raporun her detayı.</span>','Aracı döndürün, bir parçaya dokunun ve ekspertiz bulgusunu inceleyin.'],capture:['Fotoğraf çekimi','Doğru açı. <span>Eksiksiz kayıt.</span>','Personele adım adım yol gösteren standart çekim akışı.'],plan:['Sistem & kurulum','Bir şubeden başlayın. <span>Ototr ağına taşıyın.</span>','Ekipman, yazılım ve entegrasyon için uygulanabilir pilot planı.']}[next];
  $('#crumb').textContent=text[0];$('#page-title').innerHTML=text[1];$('#page-description').textContent=text[2];$('#customer-toggle').hidden=next!=='report';
  if(next==='capture')renderCapture();if(next==='report')requestAnimationFrame(()=>viewer?.resize());
}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{if(customer&&b.dataset.page!=='report'){toast('Düzenleme alanı için müşteri önizlemesinden çıkın.');return;}showPage(b.dataset.page);}));
$('.brand').addEventListener('click',e=>{e.preventDefault();showPage('report');});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
$('#part-filter').addEventListener('change',e=>{filter=e.target.value;renderParts();});
$('#edit-form').addEventListener('submit',async e=>{e.preventDefault();if(customer)return;try{state.findings[selected]=validateFinding(selected,{status:$('#edit-status').value,measurements:$('#measurement-field').hidden?'':$('#edit-measurements').value,note:$('#edit-note').value});await persist();$('#edit-dialog').close();viewer?.update(state.findings,selected);renderSummary();renderPart();renderParts();}catch(err){$('#edit-error').textContent=err.message;}});
$('#export-report').addEventListener('click',()=>{download('ototr-3d-rapor-taslagi.json',JSON.stringify(makeReport(state.findings,state.photos,state.mode),null,2));toast('Rapor taslağı indirildi. Fotoğraf dosyaları JSON içine dahil edilmez.');});
$('#export-model').addEventListener('click',async()=>{if(!viewer){toast('3D görüntüleyici kullanılamıyor.');return;}const button=$('#export-model');button.disabled=true;try{download('ototr-semantik-sedan.glb',await viewer.exportGLB(),'model/gltf-binary');toast('25 parça kimliği içeren temsili GLB modeli indirildi.');}catch{toast('3D model dışa aktarılamadı.');}finally{button.disabled=false;}});
function setCustomer(value){customer=value;document.body.classList.toggle('customer-mode',value);$('#customer-banner').hidden=!value;$('#customer-toggle').innerHTML=icon(value?'edit':'eye')+(value?' Uzman görünümü':' Müşteri görünümü');renderPart();}
$('#customer-toggle').addEventListener('click',()=>setCustomer(!customer));$('#exit-customer').addEventListener('click',()=>setCustomer(false));
$('#color-view').addEventListener('click',()=>setColor(true));$('#plain-view').addEventListener('click',()=>setColor(false));
function setColor(value){viewer?.update(state.findings,selected,value);$('#color-view').classList.toggle('active',value);$('#plain-view').classList.toggle('active',!value);$('#color-view').setAttribute('aria-pressed',value);$('#plain-view').setAttribute('aria-pressed',!value);}
$('#reset-view').addEventListener('click',()=>viewer?.view());$('#top-view').addEventListener('click',()=>viewer?.view(90,78,7.8));
$('#rotate-toggle').addEventListener('click',e=>{if(!viewer)return;viewer.controls.autoRotate=!viewer.controls.autoRotate;e.currentTarget.setAttribute('aria-pressed',viewer.controls.autoRotate);});
$('#explode-toggle').addEventListener('click',e=>{if(!viewer)return;viewer.exploded=!viewer.exploded;e.currentTarget.setAttribute('aria-pressed',viewer.exploded);});
for(const [id,multiplier] of [['zoom-in',.85],['zoom-out',1.18]])$('#'+id).addEventListener('click',()=>{if(!viewer)return;const offset=viewer.camera.position.clone().sub(viewer.controls.target);offset.setLength(Math.max(4,Math.min(13,offset.length()*multiplier)));viewer.camera.position.copy(viewer.controls.target).add(offset);viewer.controls.update();});
$('#prev-shot').addEventListener('click',()=>stepShot(-1));$('#next-shot').addEventListener('click',()=>stepShot(1));
function stepShot(delta){const i=Math.max(0,Math.min(SHOTS.length-1,SHOTS.findIndex(s=>s.id===activeShot)+delta));activeShot=SHOTS[i].id;renderCapture();}
$('#photo-upload').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const slot=activeShot;try{const photo=await preparePhoto(file,state.photos,slot);state.photos[slot]=photo;const saved=await persist();renderCapture();renderPart();renderFilmstrip();if(saved)toast('Fotoğraf eklendi. Açı ve netlik için uzman kontrolü gerekir.');}catch(err){toast(err.message);}finally{e.target.value='';}});
$('#remove-photo').addEventListener('click',async()=>{delete state.photos[activeShot];await persist();renderCapture();renderPart();renderFilmstrip();});
$('#new-capture').addEventListener('click',()=>$('#new-dialog').showModal());
$('#confirm-new').addEventListener('click',async()=>{state={findings:createFindings(false),photos:{},mode:'capture'};await persist();$('#new-dialog').close();activeShot=SHOTS[0].id;viewer?.update(state.findings,selected);renderSummary();renderPart();renderParts();renderFilmstrip();renderCapture();toast('24 pozluk boş çekim açıldı. Parçalar henüz değerlendirilmedi.');});

$('#plan-page').innerHTML=`
  <div class="plan-intro"><div><span class="eyebrow">ÖNERİLEN BAŞLANGIÇ</span><h2>Fotoğraf kanıtı +<br/>parçalanmış 3D araç modeli.</h2><p>İlk pilotta güvenilir bir müşteri sunumu kurun. Araçtan birebir 3D üretimini ayrı bir teknik deneme olarak doğrulayın.</p><span class="plan-tag">24 POZ · 25 SEÇİLEBİLİR PARÇA · UZMAN ONAYI</span></div><div class="plan-flow"><div>${icon('camera')}<span>Yönlendirilmiş çekim<small>Personel · mobil</small></span><b>01</b></div><div>${icon('target')}<span>Parçaya bağlı bulgular<small>Uzman · ölçüm + fotoğraf</small></span><b>02</b></div><div>${icon('cube')}<span>3D müşteri raporu<small>Onaylı rapora erişim</small></span><b>03</b></div></div>
  <div class="section-heading"><div><h2>Şube için ekipman seti</h2><span>Önce mevcut cihazlarla 10 araçlık pilot yapın; sonra satın almayı netleştirin.</span></div></div>
  <div class="equipment-grid">
    <article>${icon('phone')}<span>01 / ÇEKİM</span><h3>Telefon + sabit tutuş</h3><p>İyi ana kameralı bir telefon, 1× lens, 12 MP veya üstü çekim. AE/AF kilidi, telefon tutacağı ve yedek güç.</p><b>MVP için mevcut telefon yeterli olabilir</b></article>
    <article>${icon('sun')}<span>02 / ORTAM</span><h3>Yaygın, sabit aydınlatma</h3><p>2–4 difüz LED panel; karışık gün ışığını azaltan alan. Zeminde 30° konum işaretleri ve sabit araç park çizgisi.</p><b>Başlangıç hedefi: yaklaşık 6 × 8 m alan</b></article>
    <article>${icon('target')}<span>03 / ÖLÇÜM</span><h3>Kalibre boya ölçer</h3><p>Çelik ve alüminyuma uygun Fe/NFe cihaz, kalibrasyon plakaları ve inceleme lambası. Plastik için ayrı yöntem gerekir.</p><b>Boya / değişim kararını uzman verir</b></article>
    <article>${icon('monitor')}<span>04 / 3D DENEMESİ</span><h3>İsteğe bağlı iş istasyonu</h3><p>Fotogrametri denemesi için 32–64 GB RAM, NVIDIA CUDA uyumlu GPU ve hızlı SSD planlayın. Kesin seçim veri seti testine bağlıdır.</p><b>Şablon tabanlı MVP için gerekli değil</b></article>
  </div>
  <div class="comparison-card"><div class="section-heading"><div><h2>Üç farklı sonuç, üç farklı yöntem</h2><span>Fotoğraf turu, semantik model ve gerçek rekonstrüksiyon aynı şey değildir.</span></div></div><div class="table-scroll"><table><thead><tr><th>Yöntem</th><th>Çekim önerisi</th><th>Müşteriye sunduğu</th><th>Ototr kararı</th></tr></thead><tbody><tr><td><strong>Fotoğraf + 3D parça haritası</strong><small>Bu çalışan örneğin yöntemi</small></td><td>24 standart poz + bulgu detayları</td><td>Serbest döndürme, parça seçimi, uzman notu ve fotoğraf kanıtı</td><td><span class="recommended">İLK PİLOT</span></td></tr><tr><td><strong>360° gerçek fotoğraf turu</strong><small>Görüntü dizisi; geometri üretmez</small></td><td>36–72 eşit açılı kare</td><td>Aracın gerçek görünümü, sınırlı düşey bakış</td><td>İkinci geliştirme</td></tr><tr><td><strong>Fotogrametri / gerçek tarama</strong><small>RealityScan veya Metashape</small></td><td>Başlangıç denemesi: 120–240 kare, 3 yükseklik</td><td>Araca özel yüzey ve doku; ayrıca parça eşleştirme gerekir</td><td>Önce kalite deneyi</td></tr></tbody></table></div><p class="table-note">Bu çekim sayıları pilot önerisidir; rekonstrüksiyon garantisi değildir. Parlak boya, cam, yansımalar ve yetersiz örtüşme modeli bozabilir.</p></div>
  <div class="software-grid"><article><h3>Yazılım bileşenleri</h3><ul><li><strong>Mobil çekim:</strong> Ototr usta uygulamasında atanmış iş emrinden başlayan poz listesi.</li><li><strong>Web görüntüleyici:</strong> Three.js, GLB/glTF model ve sabit parça kimlikleri.</li><li><strong>Veri:</strong> İş emri → fotoğraf → parça bulgusu → teknik onay → rapor sürümü.</li><li><strong>Gerçek 3D işçisi:</strong> Sunucudaki kuyruktan çalışan ayrı GPU işlemi; tarayıcı içinde rekonstrüksiyon yapılmaz.</li><li><strong>Model hazırlığı:</strong> Blender ile parçaları ayırma, adlandırma ve GLB optimizasyonu.</li></ul></article><article><h3>Kaynaklar ve lisanslar</h3><ul><li><a href="https://www.realityscan.com/license" target="_blank" rel="noreferrer">RealityScan lisansı ↗</a><p>Son 12 aylık geliri 1 milyon USD altındaki uygun işletmeler için ücretsiz; eşik üstü için 1.250 USD / koltuk / yıl. Koşulları şirket bazında teyit edin.</p></li><li><a href="https://dev.epicgames.com/documentation/realityscan/hardware-and-software-requirements" target="_blank" rel="noreferrer">RealityScan donanım gereksinimleri ↗</a></li><li><a href="https://www.agisoft.com/pdf/metashape_2_2_en.pdf" target="_blank" rel="noreferrer">Metashape fotoğraf çekim kılavuzu ↗</a></li><li><a href="https://threejs.org/manual/en/load-gltf.html" target="_blank" rel="noreferrer">Three.js model entegrasyonu ↗</a></li></ul><small>Kaynak kontrolü: 6 Eylül 2026. Donanım için güncel teklif alınmalıdır.</small></article></div>
  <section class="pilot-card"><div><span class="eyebrow">ENTEGRASYON YOLU</span><h2>Önce 1 şube. Sonra ölçek.</h2></div><div class="pilot-steps"><div><b>01</b><h3>Çekimi standardize et</h3><p>10 araç, en az 2 personel. Siyah, beyaz ve metalik boya çeşitlerini deneyin.</p></div><div><b>02</b><h3>Kanıtı bağla</h3><p>Parça kimliklerini Ototr kaporta alanlarıyla eşleştirin. Eksik fotoğraf ve onay kapılarını kurun.</p></div><div><b>03</b><h3>Raporu sun</h3><p>Müşteriye süreli erişim verin. Sadece teknik onaydan geçmiş rapor sürümünü açın.</p></div></div></section>
  <div class="capture-tip">${icon('shield')}<div><strong>Gerçek sistem için ayrıca yapılacaklar</strong><p>Bu modülde sunucu, kullanıcı yetkilendirmesi, gerçek fotogrametri, otomatik hasar tespiti ve canlı rapor yayını yoktur. Üretimde bayi izolasyonu, uzman kilidi, kanıt asılları, erişim denetimi, saklama politikası ve rapor sürümleme gerekir.</p></div></div>`;

renderSummary();renderParts();
try{
  viewer=new CarViewer($('#car-host'),id=>selectPart(id));viewer.update(state.findings,selected);$('.viewer-loading').remove();
  thumbs=new URLSearchParams(location.search).has('generateSamples')?await viewer.thumbnails(SHOTS):Object.fromEntries(SHOTS.map(s=>[s.id,`${import.meta.env.BASE_URL}sample-renders/${s.id}.jpg`]));
  if(state.mode==='demo'&&Object.keys(state.photos).length===0){state.photos=Object.fromEntries(SHOTS.map(s=>[s.id,{kind:'render',name:`ototr-ornek-${s.id}.jpg`,url:thumbs[s.id]}]));}
  // Sample render delivery hook, also used by the local artifact export utility.
  window.ototrSampleAssets={thumbnails:thumbs,modelOrigin:'procedural-semantic-template',reconstructedFromPhotos:false};
}catch(err){
  console.error('3D görüntüleyici başlatılamadı:',err);$('#car-host').innerHTML='<div class="webgl-error"><strong>3D görüntüleyici açılamadı.</strong><p>WebGL 2 destekli güncel bir tarayıcıda donanım hızlandırmayı açın. Parça listesi ve rapor kaydı kullanılabilir.</p></div>';
}
renderPart();renderFilmstrip();renderCapture();
