import './presentation.css';
import {PresentationCar} from './presentation-car.js';
import {PhotographicCar} from './photographic-car.js';
import {PHOTO_MASK_FRAMES,referenceMask,frameForPhotoPart} from './photo-mask-domain.js';
import {makeDemoPresentation,fromApprovedReport,buildTour,getSummary} from './presentation-domain.js';
import {OUTCOMES,PROCESSES,DEFECTS} from './pilot-domain.js';
import {BEST_FRAME,directionForFrame} from './spin-domain.js';
import * as api from './pilot-api.js';

const root=document.querySelector('#presentation-app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={cube:'m12 2 9 5v10l-9 5-9-5V7l9-5Z M3 7l9 5 9-5 M12 12v10',camera:'M4 6h4l2-3h4l2 3h4v14H4V6Z M16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',left:'m14 5-7 7 7 7',right:'m10 5 7 7-7 7',rotate:'M20 7v5h-5 M20 12a8 8 0 1 0-2 6',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',close:'m6 6 12 12 M6 18 18 6',play:'m8 4 12 8-12 8V4Z',pause:'M8 4v16 M16 4v16',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',home:'m3 11 9-8 9 8 M5 10v11h14V10 M10 21v-7h4v7',arrow:'M5 12h14 m-5-5 5 5-5 5',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z m-4 10 3 3 5-6'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.cube}"/></svg>`;
const affected=p=>p.outcome==='inspected'&&((p.process!=='none'&&p.process!=='original')||p.defects.length);
let presentation=null,renderer=null,photographic=null,steps=[],selected='',mode='exploded',separation=.72,view='cutout',ghost=false,rotating=false,frame=22,evidenceIndex=0,playing=false,tourTimer=null,tourStarted=0,animation=null,lastAnchor=0,refreshTimer=null,refreshing=false,closed=false,noticeTimer,photoOrbitTimer;
const params=new URLSearchParams(location.hash.slice(1)),hasReport=params.has('rapor'),token=params.get('rapor')||'';
function tell(message){const el=document.querySelector('#announcement');clearTimeout(noticeTimer);el.textContent=message;el.className='visible';noticeTimer=setTimeout(()=>{el.className='';el.textContent='';},4500);}
function badge(){return `<span class="pill ${presentation?.kind==='approved'?'approved':'demo'}">${presentation?.kind==='approved'?'✓ Onaylı müşteri raporu':'ÖRNEK SUNUM'}</span>`;}
function current(){return presentation.parts.find(p=>p.id===selected)||presentation.parts[0];}
function header(){return `<header class="topbar"><a class="identity" href="${hasReport?'./pilot.html#rapor='+esc(token):'./pilot.html'}" aria-label="OTOTR Kaporta 360"><span class="brand">OTOTR<span>.</span></span><i class="brand-line"></i><span class="product-name">KAPORTA 360</span></a><div class="top-actions">${badge()}<a class="back-label" href="${hasReport?'./pilot.html#rapor='+esc(token):'./pilot.html'}">${hasReport?'Rapor görünümü':'Personel ekranı'}</a><button class="button primary" data-action="fullscreen" aria-label="Tam ekran sunum">${icon('expand')}<span>Sunum modu</span></button></div></header>`;}
function mount(){
  const s=getSummary(presentation);steps=buildTour(presentation);
  selected=presentation.kind==='demo'?'left_front_door':steps[0]?.partId||presentation.parts[0].id;
  frame=steps.find(s=>s.partId===selected)?.frame||BEST_FRAME[selected]||1;
  root.innerHTML=`<div class="presenter">${header()}<main class="page"><section class="page-intro"><div><div class="eyebrow">PARÇA PARÇA, AÇIK BİR İNCELEME</div><h1>Aracın hikâyesi. <span>Tüm ayrıntılarıyla.</span></h1><p class="vehicle-label"><span class="plate">${esc(presentation.vehicle.plate||'Plaka belirtilmedi')}</span> ${esc(presentation.vehicle.label)} · ${esc(presentation.vehicle.bodyType)}</p><span class="pill mobile-badge ${presentation.kind==='demo'?'demo':'approved'}">${presentation.kind==='demo'?'Örnek araç · Temsili bulgular':'Onaylı müşteri raporu'}</span></div><div class="intro-right"><div class="summary-count"><strong>${s.total}</strong><small>kaporta parçası</small></div><div class="summary-count"><strong>${s.affected.toString().padStart(2,'0')}</strong><small>${presentation.kind==='demo'?'temsili bulgu':'bulgulu parça'}</small></div><div class="summary-count"><strong>${s.photos}</strong><small>${presentation.kind==='demo'?'gerçek referans kare':'kayıtlı fotoğraf'}</small></div></div></section>
  <section class="experience" aria-label="Etkileşimli kaporta sunumu"><div class="studio"><div class="studio-toolbar"><div class="view-tabs" role="group" aria-label="Görünüm"><button data-action="view" data-view="cutout" aria-pressed="true" ${presentation.kind!=='demo'?'disabled title="Bu rapora özel fotoğraf konturları henüz hazırlanmamış."':''}>${icon('camera')} Fotoğraftan parçalar</button><button data-action="view" data-view="photo" aria-pressed="false">24 fotoğraf</button><button data-action="view" data-view="model" aria-pressed="false">${icon('cube')} 3D şema</button></div><div class="studio-tag" id="studio-tag"><i></i> GERÇEK FOTOĞRAF / GÖRÜNÜR YÜZEYLER</div></div><div class="scene loading" data-selected="${selected}"><div class="scene-host" role="group" aria-label="3D araç. Döndürmek için sürükleyin; bir parçaya tıklayarak seçin. Klavye ile aşağıdaki parça listesini kullanabilirsiniz."></div><div class="photo-layer-host" aria-label="Gerçek fotoğraftan ayrılan araç parçaları"></div><div class="scene-hud"><div class="eyebrow">PARÇAYA TIKLAYIN, YAKINDAN İNCELEYİN</div><h2 id="scene-title">Kaporta, katman katman.</h2><p id="scene-help">Gövdeyi sürükleyerek çevirin.<br>Bir parçaya dokunarak öne alın.</p></div><div class="model-label" id="model-label"></div><div class="scene-caption" id="scene-caption">${icon('camera')} Gerçek fotoğraf dokusu korunur</div><div class="photo-stage" id="photo-stage"></div></div>
  <div class="studio-controls"><div class="assembly-controls" role="group" aria-label="Parçaları görüntüleme"><button data-action="mode" data-mode="assembled" aria-pressed="false">Birleştir</button><button data-action="mode" data-mode="exploded" aria-pressed="true">Parçaları ayır</button><button data-action="mode" data-mode="isolate" aria-pressed="false">Tek parça</button></div><label class="separation"><span>Açılma</span><input id="separation" type="range" min="0" max="100" value="72" aria-label="Parçaların ayrılma mesafesi"></label><div class="control-icons"><button class="icon-button" data-action="ghost" aria-label="Diğer parçaları saydamlaştır" title="Diğer parçaları saydamlaştır" aria-pressed="false">${icon('eye')}</button><button class="icon-button" data-action="rotate" aria-label="Otomatik döndür" title="Otomatik döndür" aria-pressed="false">${icon('rotate')}</button><button class="icon-button" data-action="home" aria-label="Genel görünüme dön" title="Genel görünüme dön">${icon('home')}</button></div><div class="photo-controls"><button data-action="frame-prev" aria-label="Önceki fotoğraf açısı">${icon('left')}</button><input id="photo-frame" type="range" min="1" max="24" value="${frame}" aria-label="24 fotoğraf açısı"><span id="frame-count"></span><button data-action="frame-next" aria-label="Sonraki fotoğraf açısı">${icon('right')}</button></div></div><div class="photo-angle-strip" id="photo-angle-strip" aria-label="Parça sınırları hazırlanmış fotoğraf açıları"></div><p class="studio-source" id="studio-source">Fotoğraftaki görünür dış yüzeyler ayrı katmanlarda hareket eder. İç yapı veya parçaların arka yüzleri üretilmez.</p></div><aside class="evidence-panel" id="evidence-panel" aria-label="Seçili parçanın incelemesi"></aside></section>
  <section class="tour-bar" aria-label="Bulgu anlatımı"><div class="tour-title"><b>Birlikte inceleyelim.</b><small>${steps.length?steps.length+' bulgu · Adım adım sunum':'Bu raporda bulgu turu yok'}</small></div><div class="tour-stops" id="tour-stops"></div><div class="tour-action"><button class="button gold" data-action="tour" aria-pressed="false" ${!steps.length?'disabled':''}>${icon('play')} Anlatımı başlat</button><div class="tour-progress" aria-hidden="true"><span></span></div></div></section>
  <details class="parts-drawer"><summary>Tüm parçaları keşfedin <span>${s.inspected} incelendi · ${s.unchecked} inceleme kaydı yok &nbsp; ＋</span></summary><div class="part-chips">${presentation.parts.map(p=>`<button class="part-chip ${affected(p)?'affected':''}" data-action="part" data-id="${p.id}" aria-pressed="${p.id===selected}"><i></i>${esc(p.name)}</button>`).join('')}</div></details>
  <footer class="footer"><p class="source-note">${esc(presentation.disclaimer)}${presentation.kind==='demo'?` <a href="${esc(presentation.source.url)}" target="_blank" rel="noreferrer">Fotoğraf: SpinFrame / WebRotate 360</a>. Ticari kullanım izni doğrulanmadı.`:''}</p><p>${presentation.kind==='approved'?'Teknik onay: '+esc(presentation.approvedBy||'Kayıtlı uzman')+' · '+esc(new Date(presentation.approvedAt).toLocaleDateString('tr-TR')):'OTOTR / Müşteri deneyimi prototipi'}<br>Ölçüm tek başına işlem veya hasar sonucu belirlemez.</p></footer></main></div><dialog class="photo-dialog"><header><strong id="dialog-title"></strong><button class="icon-button" data-action="close-photo" aria-label="Fotoğrafı kapat">${icon('close')}</button></header><div class="annotation-wrap" id="dialog-media"></div><p id="dialog-caption"></p></dialog>`;
  root.querySelector('.presenter').append(root.querySelector('dialog'));
  if(view==='model')ensureModel();
  root.querySelector('.scene-host').addEventListener('presentation-error',fallback);
  root.querySelector('.scene').classList.remove('loading');
  renderSelection();updateControls();animation=requestAnimationFrame(tick);
}
function fallback(){pauseTour();renderer?.dispose();renderer=null;root.querySelector('.scene-host').innerHTML='<div class="scene-fallback"><p>Bu cihazda 3D görünüm açılamadı.<br>Fotoğrafları ve tüm parça kayıtlarını inceleyebilirsiniz.</p><button class="button" data-action="view" data-view="photo">Gerçek fotoğraflara geç →</button></div>';root.querySelector('.model-label').style.display='none';root.querySelectorAll('[data-action="mode"],[data-action="ghost"],[data-action="rotate"],[data-action="home"],#separation').forEach(b=>b.disabled=true);}
function ensureModel(){if(renderer)return;try{renderer=new PresentationCar(root.querySelector('.scene-host'),{profile:presentation.profile,onSelect:id=>select(id)});renderer.setFindings(Object.fromEntries(presentation.parts.map(p=>[p.id,p])));renderer.setExplode(separation);renderer.selectPart(selected,{focus:false});renderer.setMode(mode);renderer.setGhost(ghost);}catch{fallback();}}
function stopRotation(){clearInterval(photoOrbitTimer);photoOrbitTimer=null;rotating=false;renderer?.setAutoRotate(false);}
function renderCutout(){
  if(view!=='cutout')return;
  const mask=referenceMask(presentation,frame),photo=presentation.photos.find(p=>p.frame===frame);
  if(!mask||!photo){photographic?.dispose();photographic=null;root.querySelector('.photo-layer-host').innerHTML='<div class="photo-empty">Bu fotoğraf için doğrulanmış parça sınırları bulunmuyor.</div>';return;}
  if(!photographic)photographic=new PhotographicCar(root.querySelector('.photo-layer-host'),{onSelect:id=>select(id),names:Object.fromEntries(presentation.parts.map(p=>[p.id,p.name]))});
  photographic.setSource({photo,mask});photographic.selectPart(selected);photographic.setExplode(separation);photographic.setMode(mode);photographic.setGhost(ghost);
  root.querySelector('#photo-angle-strip').innerHTML=PHOTO_MASK_FRAMES.map(f=>`<button data-action="photo-angle" data-frame="${f}" aria-label="${esc(directionForFrame(f))} fotoğrafından parçalar" aria-pressed="${frame===f}"><img src="./real-car/frame-${String(f).padStart(2,'0')}.jpg" alt="" loading="lazy"><span>${esc(directionForFrame(f))}</span></button>`).join('');
}
function photoAngle(n,{automatic=false}={}){if(!automatic){pauseTour();stopRotation();}const mask=referenceMask(presentation,n);if(!mask)return;frame=n;if(!mask.parts.some(p=>p.id===selected))selected=mask.parts.find(p=>p.id.includes('door'))?.id||mask.parts[0].id;evidenceIndex=0;renderSelection();updateControls();}
function annotationSVG(p){return p?.annotations?.length?`<svg class="annotation-svg" viewBox="0 0 1 1" preserveAspectRatio="none" aria-label="Uzmanın işaretlediği alan">${p.annotations.map(a=>`<rect x="${a.x}" y="${a.y}" width="${a.w}" height="${a.h}"/>`).join('')}</svg>`:'';}
function media(p){return `<img src="${esc(p.url)}" alt="${esc(current().name+' · '+p.caption)}" referrerpolicy="no-referrer">${annotationSVG(p)}`;}
function fitMarks(container){if(!container?.isConnected)return;const img=container.querySelector('img'),svg=container.querySelector('.annotation-svg');if(!img||!svg||!img.naturalWidth)return;const scale=Math.min(img.clientWidth/img.naturalWidth,img.clientHeight/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;Object.assign(svg.style,{width:w+'px',height:h+'px',left:(img.offsetLeft+(img.clientWidth-w)/2)+'px',top:(img.offsetTop+(img.clientHeight-h)/2)+'px'});}
function hydrateImages(){root.querySelectorAll('img').forEach(img=>{img.onload=()=>{if(img.isConnected)fitMarks(img.parentElement);};img.onerror=()=>{if(!img.isConnected)return;const container=img.parentElement;container.querySelector('.annotation-svg')?.remove();img.remove();const message=document.createElement('p');message.className='no-evidence';message.textContent='Fotoğraf yüklenemedi. Görünümü yenileyerek tekrar deneyin.';container.append(message);};if(img.complete)fitMarks(img.parentElement);});}
function renderSelection(){const p=current(),index=presentation.parts.findIndex(p=>p.id===selected),ph=p.evidence[evidenceIndex%Math.max(1,p.evidence.length)];const state=p.outcome==='inspected'?PROCESSES[p.process]:OUTCOMES[p.outcome];
  root.querySelector('#evidence-panel').innerHTML=`<div class="panel-scroll"><div class="panel-kicker"><span class="eyebrow">${esc(p.group)} / ${presentation.kind==='demo'?'ÖRNEK KAYIT':'UZMAN KAYDI'}</span><span class="panel-index">${String(index+1).padStart(2,'0')} / ${presentation.parts.length}</span></div><h2 id="part-title">${esc(p.name)}</h2><div class="row status-row"><span class="status-label ${p.outcome==='inspected'?p.process:'unchecked'}">${esc(state)}</span>${p.defects.map(d=>`<span class="defect-label">${esc(DEFECTS[d])}</span>`).join('')}</div><p class="explanation">${esc(p.explanation)}</p>${p.measurements.length?`<div class="readings">${p.measurements.map((m,i)=>`<div class="reading"><strong>${m.toLocaleString('tr-TR')}</strong><small>Nokta ${i+1} · µm</small></div>`).join('')}</div>`:''}<div class="evidence-block"><div class="evidence-media">${ph?media(ph)+`<button class="zoom-photo" data-action="zoom-photo" aria-label="Bağlı fotoğrafı büyüt">${icon('expand')}</button>`:'<div class="no-evidence">Bu parçaya bağlı fotoğraf bulunmuyor.</div>'}</div><div class="evidence-caption"><span>${esc(ph?.caption||'Uzman kaydında bağlı fotoğraf yok.')}</span>${p.evidence.length>1?`<div class="photo-pagination"><button data-action="evidence-prev" aria-label="Önceki bağlı fotoğraf">${icon('left')}</button><button data-action="evidence-next" aria-label="Sonraki bağlı fotoğraf">${icon('right')}</button></div>`:''}</div></div><div class="expert-note"><div class="eyebrow">${presentation.kind==='demo'?'TEMSİLİ UZMAN NOTU':'UZMANIN AÇIKLAMASI'}</div><p>${esc(p.note||'Bu parça için ek açıklama kaydedilmemiş.')}</p></div></div><div class="part-nav"><button data-action="part-prev" aria-label="Önceki parça">${icon('left')} Önceki</button><small>${p.material==='metal'?'Metal yüzey':p.material==='glass'?'Cam yüzey':'Plastik yüzey'}</small><button data-action="part-next" aria-label="Sonraki parça">Sonraki ${icon('right')}</button></div>`;
  root.querySelector('.scene').dataset.selected=selected;
  root.querySelector('#model-label').innerHTML=`<span>${String(index+1).padStart(2,'0')}</span>${esc(p.name)}`;
  root.querySelectorAll('.part-chip').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===selected));
  root.querySelector('#tour-stops').innerHTML=steps.length?steps.map((s,i)=>`<button class="tour-stop ${s.partId===selected?'active':''}" data-action="part" data-id="${s.partId}" aria-current="${s.partId===selected?'step':'false'}"><span class="number">0${i+1}</span><div><b>${esc(s.title)}</b><small>${esc(PROCESSES[s.process])}</small></div><i class="stop-dot ${s.process}"></i></button>`).join(''):'<small class="muted">Parça listesinden kayıtları tek tek inceleyebilirsiniz.</small>';
  renderPhoto();renderCutout();hydrateImages();
}
function renderPhoto(){const ph=presentation.photos.find(p=>p.frame===frame);root.querySelector('#photo-stage').innerHTML=ph?`<img src="${esc(ph.url)}" alt="${esc(ph.caption)}" draggable="false" referrerpolicy="no-referrer"><span class="photo-badge">${esc(directionForFrame(frame))} · ${presentation.kind==='demo'?'Gerçek referans fotoğraf':'Kayıtlı araç fotoğrafı'}</span>`:`<div class="photo-empty">${esc(directionForFrame(frame))}<br>Bu açıya ait kayıtlı fotoğraf bulunmuyor.</div>`;root.querySelector('#frame-count').textContent=String(frame).padStart(2,'0')+' / 24';root.querySelector('#photo-frame').value=frame;hydrateImages();}
function select(id,{tour=false,focus=true}={}){if(!presentation?.parts.some(p=>p.id===id))return;if(!tour)pauseTour();stopRotation();selected=id;evidenceIndex=0;if(view==='cutout'){const chosen=frameForPhotoPart(id,frame);if(chosen)frame=chosen;else{view='photo';frame=BEST_FRAME[id]||1;tell('Bu parçanın fotoğraf sınırları henüz hazırlanmadı. Kayıtlı genel görünümü açtım.');}}else frame=steps.find(s=>s.partId===id)?.frame||BEST_FRAME[id]||1;renderer?.selectPart(id,{focus});renderSelection();updateControls();}
function updateControls(){
  if(!presentation)return;
  root.querySelectorAll('[data-action="mode"]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.mode===mode);b.disabled=view==='model'&&!renderer;});
  root.querySelectorAll('[data-action="view"]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));
  root.querySelector('[data-action="ghost"]').setAttribute('aria-pressed',ghost);root.querySelector('[data-action="rotate"]').setAttribute('aria-pressed',rotating);
  root.querySelectorAll('[data-action="ghost"],[data-action="rotate"],[data-action="home"],#separation').forEach(b=>b.disabled=view==='model'&&!renderer);
  root.querySelector('.studio').classList.toggle('photo-mode',view==='photo');root.querySelector('.studio').classList.toggle('cutout-mode',view==='cutout');
  root.querySelector('.scene').dataset.mode=mode;root.querySelector('.scene').dataset.view=view;root.querySelector('.scene').dataset.separation=String(separation);root.querySelector('#separation').value=separation*100;
  root.querySelector('#scene-title').textContent=view==='cutout'?(mode==='assembled'?'Gerçek çekim. Tek bir bütün.':mode==='isolate'?'Gerçek yüzey, yakından.':'Fotoğrafın içinden, parça parça.'):(mode==='assembled'?'Bir bütün, pek çok ayrıntı.':mode==='isolate'?'Tüm dikkat, tek parçada.':'Kaporta, katman katman.');
  root.querySelector('#scene-help').textContent=view==='cutout'?'Fotoğraftaki parçaya dokunun. Boya ve yansımalar özgün kareden gelir.':'Gövdeyi sürükleyerek çevirin. Bir parçaya dokunarak öne alın.';
  root.querySelector('#studio-tag').innerHTML='<i></i>'+ (view==='cutout'?'8 AÇI / GERÇEK FOTOĞRAF KATMANLARI':view==='photo'?'24 AÇI / KAYITLI FOTOĞRAF':'TEMSİLİ 3D GÖVDE');
  root.querySelector('#scene-caption').innerHTML=icon(view==='cutout'?'camera':'rotate')+(view==='cutout'?' Özgün fotoğraf · Görünür yüzeyler':' Sürükle: döndür · Kaydır: yakınlaş');
  root.querySelector('#studio-source').textContent=view==='cutout'?'Fotoğraftaki görünür dış yüzeyler ayrı katmanlarda hareket eder. İç yapı veya parçaların arka yüzleri üretilmez.':view==='model'?'3D gövde, parça konumunu anlatan temsili bir modeldir. Fotoğraflardan üretilmez; iç yapı ve mekanik durum göstermez.':'24 kayıtlı fotoğraf arasında çevre turu. Fotoğrafın aslı değiştirilmez.';
  root.querySelector('[data-action="rotate"]').setAttribute('aria-label',view==='cutout'?'Hazırlanmış açıları sırayla göster':'Otomatik döndür');
}
function pauseTour(){clearTimeout(tourTimer);playing=false;const button=root.querySelector('[data-action="tour"]');if(button){button.setAttribute('aria-pressed','false');button.innerHTML=icon('play')+' Anlatımı başlat';}const progress=root.querySelector('.tour-progress span');if(progress)progress.style.width='0';}
function advanceTour(index){if(index>=steps.length){pauseTour();tell('Bulgu anlatımı tamamlandı. Diğer parçaları da inceleyebilirsiniz.');return;}select(steps[index].partId,{tour:true});tourStarted=performance.now();tourTimer=setTimeout(()=>advanceTour(index+1),7500);}
function startTour(){if(!steps.length)return;playing=true;stopRotation();mode='exploded';renderer?.setMode(mode);photographic?.setMode(mode);updateControls();const b=root.querySelector('[data-action="tour"]');b.setAttribute('aria-pressed','true');b.innerHTML=icon('pause')+' Anlatımı duraklat';advanceTour(0);}
function tick(time){if(closed)return;if(playing){const el=root.querySelector('.tour-progress span');if(el)el.style.width=Math.min(100,(time-tourStarted)/75)+'%';}if(time-lastAnchor>100&&view!=='photo'){lastAnchor=time;const p=(view==='cutout'?photographic:renderer)?.getPartScreenPosition?.(selected),label=root.querySelector('#model-label');if(label){label.style.display=p?.visible?'block':'none';if(p){label.style.left=Math.max(.16,Math.min(.84,p.x))*100+'%';label.style.top=Math.max(.27,Math.min(.90,p.y))*100+'%';}}}animation=requestAnimationFrame(tick);}
root.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||!presentation)return;const a=b.dataset.action;
  if(a==='part')select(b.dataset.id);
  if(a==='part-prev'||a==='part-next'){const i=presentation.parts.findIndex(p=>p.id===selected);select(presentation.parts[(i+(a==='part-next'?1:presentation.parts.length-1))%presentation.parts.length].id);}
  if(a==='mode'){pauseTour();stopRotation();mode=b.dataset.mode;if(mode==='exploded'&&separation===0){separation=.72;renderer?.setExplode(separation);photographic?.setExplode(separation);}renderer?.setMode(mode);photographic?.setMode(mode);updateControls();}
  if(a==='view'){pauseTour();stopRotation();view=b.dataset.view;if(view==='cutout'){frame=frameForPhotoPart(selected,frame)||22;const mask=referenceMask(presentation,frame);if(mask&&!mask.parts.some(p=>p.id===selected))selected=mask.parts[0].id;renderSelection();}if(view==='model'){ensureModel();renderer?.setExplode(separation);renderer?.selectPart(selected,{focus:false});renderer?.setMode(mode);renderer?.setGhost(ghost);}updateControls();}
  if(a==='photo-angle')photoAngle(Number(b.dataset.frame));
  if(a==='ghost'){pauseTour();ghost=!ghost;renderer?.setGhost(ghost);photographic?.setGhost(ghost);updateControls();}
  if(a==='rotate'){pauseTour();if(rotating)stopRotation();else if(view==='cutout'){if(matchMedia('(prefers-reduced-motion: reduce)').matches)tell('Hareket azaltma açık. Açıları aşağıdaki fotoğraflardan seçebilirsiniz.');else{rotating=true;photoOrbitTimer=setInterval(()=>photoAngle(PHOTO_MASK_FRAMES[(PHOTO_MASK_FRAMES.indexOf(frame)+1)%PHOTO_MASK_FRAMES.length],{automatic:true}),2600);}}else{rotating=true;renderer?.setAutoRotate(true);}updateControls();}
  if(a==='home'){pauseTour();stopRotation();mode='assembled';ghost=false;renderer?.home();renderer?.selectPart(selected,{focus:false});photographic?.home();updateControls();}
  if(a==='frame-next'||a==='frame-prev'){pauseTour();frame=(frame+(a==='frame-next'?0:22))%24+1;renderPhoto();}
  if(a==='evidence-next'||a==='evidence-prev'){pauseTour();evidenceIndex=(evidenceIndex+(a==='evidence-next'?1:current().evidence.length-1))%current().evidence.length;renderSelection();}
  if(a==='tour')playing?pauseTour():startTour();
  if(a==='zoom-photo'){pauseTour();const p=current().evidence[evidenceIndex%current().evidence.length];if(p){root.querySelector('#dialog-title').textContent=current().name;root.querySelector('#dialog-media').innerHTML=media(p);root.querySelector('#dialog-caption').textContent=p.caption;root.querySelector('dialog').showModal();hydrateImages();}}
  if(a==='close-photo')root.querySelector('dialog').close();
  if(a==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.querySelector('.presenter').requestFullscreen();}catch{tell('Bu tarayıcı tam ekranı desteklemiyor. Yatay ekranı kullanabilirsiniz.');}}
});
root.addEventListener('input',e=>{if(e.target.id==='separation'){pauseTour();stopRotation();separation=Number(e.target.value)/100;mode='exploded';renderer?.setMode(mode);renderer?.setExplode(separation);photographic?.setExplode(separation);photographic?.setMode(mode);updateControls();}if(e.target.id==='photo-frame'){pauseTour();frame=Number(e.target.value);renderPhoto();}});
document.addEventListener('keydown',e=>{if(e.defaultPrevented||!presentation||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,button,a,summary,dialog'))return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();root.querySelector(`[data-action="${view==='photo'?'frame':'part'}-${e.key==='ArrowRight'?'next':'prev'}"]`).click();}if(e.code==='Space'){e.preventDefault();playing?pauseTour():startTour();}});
window.addEventListener('resize',()=>root.querySelectorAll('.evidence-media,.annotation-wrap').forEach(fitMarks));
window.addEventListener('hashchange',()=>location.reload());
function closeReport(message){closed=true;pauseTour();clearInterval(refreshTimer);cancelAnimationFrame(animation);renderer?.dispose();photographic?.dispose();clearInterval(photoOrbitTimer);renderer=null;photographic=null;presentation=null;steps=[];root.innerHTML=`<div class="closed-screen"><span class="brand">OTOTR.</span><h1>Sunum şu anda açılamıyor.</h1><p>${esc(message)}</p><button class="button primary" id="retry-report">Bağlantıyı yeniden kontrol et</button></div>`;root.querySelector('#retry-report').onclick=()=>location.reload();}
async function refreshReport(){if(refreshing||closed||!hasReport||document.hidden)return;refreshing=true;try{const fresh=fromApprovedReport(await api.customerReport(token));if(fresh.profile!==presentation.profile)throw Error('Rapor düzeni değişti. Bağlantıyı yeniden açın.');presentation=fresh;steps=buildTour(fresh);pauseTour();renderer?.setFindings(Object.fromEntries(fresh.parts.map(p=>[p.id,p])));root.querySelector('dialog').close();root.querySelector('#dialog-media').replaceChildren();renderSelection();}catch{closeReport('Bağlantının süresi dolmuş, paylaşımı kapatılmış veya bağlantı kesilmiş olabilir. Güncel raporu kontrol ederek yeniden deneyin.');}finally{refreshing=false;}}
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseTour();stopRotation();if(presentation)updateControls();}else refreshReport();});
window.addEventListener('pagehide',()=>{pauseTour();clearInterval(refreshTimer);cancelAnimationFrame(animation);renderer?.dispose();photographic?.dispose();clearInterval(photoOrbitTimer);presentation=null;root.replaceChildren();});
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
async function start(){try{if(hasReport){if(!/^[a-f0-9]{64}$/.test(token))throw Error('Müşteri bağlantısı geçersiz. Lütfen size iletilen rapor bağlantısını kullanın.');await api.configure();presentation=fromApprovedReport(await api.customerReport(token));}else presentation=makeDemoPresentation();if(hasReport)view='photo';mount();if(hasReport)refreshTimer=setInterval(refreshReport,90000);}catch(e){closeReport(hasReport?'Onaylı rapora erişilemedi. Bağlantının süresini ve internet erişimini kontrol edin.':e.message);}}
start();
