import './real-spin.css';
import { REAL_PARTS, STATUS, FRAME_COUNT, normalizeFrame, angleForFrame, directionForFrame, imagePath, anchorsAt, BEST_FRAME, createSpinFindings } from './spin-domain.js';
import { validateFinding } from './domain.js';
const erpMode=import.meta.env.MODE==='erp';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={camera:'M4 6h4l2-3h4l2 3h4v14H4V6Z M16 13a4 4 0 1 1-8 0 4 4 0 0 1 8 0',arrow:'M5 12h14 m-5-5 5 5-5 5',left:'m14 5-7 7 7 7',right:'m10 5 7 7-7 7',rotate:'M20 7v5h-5 M20 12a8 8 0 1 0-2 6',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',info:'M12 11v6 M12 7v1 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',close:'m6 6 12 12 M6 18 18 6',edit:'m16 3 5 5-12 12-6 1 1-6L16 3Z M14 5l5 5',download:'M12 3v12 m-5-5 5 5 5-5 M4 16v5h16v-5',pin:'M12 22s8-9 8-14a8 8 0 1 0-16 0c0 5 8 14 8 14Z M15 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0',check:'m5 12 4 4L19 6',play:'m8 4 12 8-12 8V4Z',pause:'M8 4v16 M16 4v16',grid:'M3 3h7v7H3V3Z M14 3h7v7h-7V3Z M3 14h7v7H3v-7Z M14 14h7v7h-7v-7Z',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z m-4 10 3 3 5-6',source:'M10 13a5 5 0 0 0 7 0l4-4a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-4 4a5 5 0 0 0 7 7l2-2'};
const icon=(name)=>`<svg viewBox="0 0 24 24" class="i" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
let frame=22,selected='left_front_door',zoom=1,showPins=true,playing=false,ready=false,timer=null,drag=null,filter='all',toastTimer;
let findings=createSpinFindings();const sessionKey='ototr-real-spin-example-v1';
try{const saved=JSON.parse(localStorage.getItem(sessionKey));if(saved)for(const p of REAL_PARTS)findings[p.id]=validateFinding(p.id,saved[p.id]);}catch{findings=createSpinFindings();}
$('#real-app').innerHTML=`
  <header class="r-header"><a href="./real-360.html" class="r-brand" aria-label="Ototr Vision"><span>OTO<b>TR</b><sup>®</sup></span><i></i><em>VISION</em></a><nav aria-label="Görünüm"><span class="header-active">360° araç inceleme</span><a href="./index.html">İlk tasarımı aç ${icon('arrow')}</a></nav><div class="r-account"><span class="r-demo">TASARIM 02</span><div>OT</div></div></header>
  <main class="r-main">
    <section class="r-heading"><div><div class="r-eyebrow"><span></span> GERÇEK FOTOĞRAFLARLA EKSPERTİZ DENEYİMİ</div><h1>Aracı görün.<br class="mobile-break"/><span> Her ayrıntıyı anlayın.</span></h1><p>Aynı aracın 24 farklı açısından, tek bir inceleme alanına.</p></div><button class="r-button r-primary" id="open-guide">${icon('camera')} Bu çekimi nasıl yaparım?</button></section>
    <div class="r-workspace">
      <section class="r-viewer" id="spin-viewer" aria-label="24 gerçek fotoğrafla 360 derece araç turu">
        <div class="r-vehicle-heading"><div><span class="r-overline">İNCELEMEDEKİ ARAÇ</span><h2>Opel ADAM <span>360°</span></h2><p>3 kapılı hatchback <i>·</i> Fotoğraf kaynağı: SpinFrame</p></div><div class="r-photo-badge">${icon('camera')}<span>GERÇEK ÇEKİM<strong>24 kare</strong></span></div></div>
        <div class="r-view-tabs"><span class="active">Dış görünüm</span><button id="pins-toggle" aria-pressed="true">${icon('pin')} Parça işaretleri</button><span class="r-loaded" id="frame-loaded">Kareler hazırlanıyor…</span></div>
        <div class="r-stage" id="spin-stage" tabindex="0" role="group" aria-label="360 derece fotoğraf turu. Sürükleyin veya sağ ve sol ok tuşlarını kullanın.">
          <div class="r-image-plane" id="image-plane"><img id="spin-image" src="${imagePath(22)}" alt="Opel ADAM, sol ön açıdan gerçek fotoğraf" draggable="false"/><div id="image-pins"></div></div>
          <div class="r-stage-caption"><span class="r-green-dot"></span> 24 GERÇEK FOTOĞRAF <i>/</i> 360° TUR</div>
          <div class="r-stage-controls"><button id="zoom-in-real" aria-label="Fotoğrafı yakınlaştır" title="Yakınlaştır">${icon('plus')}</button><button id="zoom-out-real" aria-label="Fotoğrafı uzaklaştır" title="Uzaklaştır">${icon('minus')}</button><span></span><button id="expand-real" aria-label="İnceleme alanını genişlet" title="Alanı genişlet" aria-pressed="false">${icon('expand')}</button></div>
          <div class="r-drag-hint">${icon('rotate')} Aracı döndürmek için sürükleyin</div><div class="r-zoom-label" id="zoom-label">1.0×</div>
        </div>
        <div class="r-transport"><div class="r-playback"><button id="previous-frame" aria-label="Önceki kare" disabled>${icon('left')}</button><button id="play-spin" class="r-play" aria-label="Otomatik döndür" aria-pressed="false" disabled>${icon('play')}</button><button id="next-frame" aria-label="Sonraki kare" disabled>${icon('right')}</button></div><div class="r-scrubber"><label for="frame-slider">${icon('rotate')} <strong id="frame-direction">Sol ön görünüm</strong><span id="frame-angle">315°</span></label><input id="frame-slider" type="range" min="1" max="24" value="22" step="1" aria-label="24 kare arasında açı seç" disabled/></div><div class="r-frame-counter"><strong id="frame-current">22</strong><span>/ 24</span></div></div>
        <div class="r-thumbnails" id="r-thumbnails"></div>
        <div class="r-photo-note">${icon('info')} Fotoğraf tabanlı 360° tur. Derinlik veya ölçülebilir 3D geometri üretilmez.</div>
      </section>
      <aside class="r-inspection"><div class="r-panel-top"><span>KAPORTA İNCELEMESİ</span><span class="r-sample-label">ÖRNEK SENARYO</span></div><div id="r-detail"></div><div class="r-related"><div><h3>Diğer örnek bulgular</h3><span id="scenario-count">3</span></div><div id="scenario-list"></div></div><div class="r-truth-note">${icon('shield')}<p>Fotoğraflar gerçek. Bulgular ve ölçümler tasarım örneğidir; bu araçta hasar tespiti yapıldığı anlamına gelmez.</p></div></aside>
    </div>
    <section class="r-lower-bar"><div><span class="r-number">24</span><p>Gerçek kare<strong>Tek araç, tam çevre turu</strong></p></div><div><span class="r-number">15°</span><p>Açı adımı<strong>24 kare için nominal sıra</strong></p></div><div><span class="r-number">23</span><p>Parça rehberi<strong>Bu kasaya göre düzenlendi</strong></p></div><button id="all-photos">${icon('grid')} 24 karenin tamamı ${icon('arrow')}</button></section>
    <section class="r-parts"><div class="r-section-title"><div><span class="r-overline">KAPORTANIN TAMAMINI KONUŞUN</span><h2>Parçayı seçin. İlgili açıya geçin.</h2><p>Bu araçta iki yan kapı bulunur. Üst ve gizli yüzeyler için ek çekim gerekir.</p></div><label>Görünüm<select id="real-filter"><option value="all">Tüm parçalar · 23</option><option value="examples">Örnek bulgular</option><option value="unchecked">Değerlendirilmemiş</option></select></label></div><div class="r-parts-grid" id="real-parts"></div></section>
    <footer class="r-footer"><p>Fotoğraflar: <a href="https://www.spinframe.com/" target="_blank" rel="noreferrer">SpinFrame</a> <i>·</i> <a href="https://www.webrotate360.com/examples/browse-all-examples/360-car-photography.aspx" target="_blank" rel="noreferrer">WebRotate 360 örnek seti ${icon('source')}</a><small>Yerel tasarım referansı. Canlı Ototr kullanım lisansı doğrulanmadı.</small></p><button id="export-real">${icon('download')} Senaryo taslağını indir</button></footer>
  </main>
  <dialog class="r-dialog" id="real-edit"><form id="real-edit-form"><div class="r-dialog-title"><div><span class="r-overline">ÖRNEK SENARYOYU DÜZENLE</span><h2 id="real-edit-name"></h2></div><button type="button" data-close="real-edit" aria-label="Kapat">${icon('close')}</button></div><div class="r-dialog-notice">Bu kayıt fotoğraftaki araca ait gerçek ekspertiz sonucu değildir.</div><label>Örnek durum<select id="real-edit-status">${Object.entries(STATUS).map(([id,s])=>`<option value="${id}">${s.label}</option>`).join('')}</select></label><label id="real-measure-field">Örnek ölçümler (µm)<input id="real-edit-measure" placeholder="248, 272, 261"/></label><label>Senaryo notu<textarea id="real-edit-note" maxlength="2000" rows="4"></textarea></label><p id="real-edit-error" role="alert"></p><div class="r-dialog-actions"><button type="button" class="r-button" data-close="real-edit">Vazgeç</button><button class="r-button r-primary" type="submit">${icon('check')} Taslağı kaydet</button></div></form></dialog>
  <dialog class="r-dialog r-gallery-dialog" id="gallery-dialog"><div class="r-dialog-title"><div><span class="r-overline">AYNI ARACIN TAM ÇEVRE TURU</span><h2>24 gerçek kare</h2></div><button data-close="gallery-dialog" aria-label="Kapat">${icon('close')}</button></div><p class="r-gallery-description">Kareye dokunarak o açıdan incelemeye devam edin. Fotoğraflar SpinFrame / WebRotate 360 örnek setindendir.</p><div id="gallery-grid" class="r-gallery-grid"></div></dialog>
  <dialog class="r-dialog r-guide-dialog" id="guide-dialog"><div class="r-dialog-title"><div><span class="r-overline">OTOTR İÇİN ÇEKİM ALTERNATİFİ</span><h2>24 kareyle gerçek araç turu</h2></div><button data-close="guide-dialog" aria-label="Kapat">${icon('close')}</button></div><div class="r-guide-lead">Buradaki 24 karenin tamamı çevre turudur. İlk tasarımdaki 12 çevre + 4 üst + 8 detay protokolünden farklıdır.</div><ol><li><strong>Aracı sabitleyin.</strong> Aynı park noktası, kapalı kapılar, sabit ışık ve aynı kamera yüksekliği kullanın.</li><li><strong>Her 15°'de bir kare çekin.</strong> Ön görünümden başlayıp tek yönde 24 poz tamamlayın. Kadraj merkezini ve mesafeyi koruyun.</li><li><strong>Fotoğrafları sıraya koyun.</strong> Gerçek görüntüler değiştirilmeden turda gösterilir. Eksik açı, başka bir araç veya yapay kareyle tamamlanmaz.</li><li><strong>Parça kanıtını ayrıca çekin.</strong> Bulgu yakın planları, boya cihazı ekranı, tavan ve iç yapısal yüzeyler bu 24 kareye ektir.</li><li><strong>Uzman kontrolüyle yayınlayın.</strong> Bu örnekteki işaretler elle yerleştirildi. Gerçek sistemde fotoğraf ve bulgu bağı teknik onaydan geçmelidir.</li></ol><a class="r-button" href="./index.html">İlk prototipin çekim akışını aç ${icon('arrow')}</a></dialog>
  <div class="r-toast" id="real-toast" role="status" aria-live="polite"></div>`;

if(erpMode){
  $('.r-brand').href='./';$('.r-brand').setAttribute('aria-label','Ototr Kaporta 360');$('.r-brand em').textContent='KAPORTA 360';
  $('.r-header nav').innerHTML=`<span class="header-active">Kaporta 360</span><a href="../index.html#dashboard">ERP'ye dön ${icon('arrow')}</a>`;
  $('.r-demo').textContent='DEMO';
  $('.r-footer small').textContent='Kaynak gösterimli demo. Fotoğrafların ticari kullanım izni doğrulanmadı.';
  $('.r-guide-lead').textContent='Bu 24 karenin tamamı çevre turudur. Tavan, bulgu yakın planları ve iç yapısal yüzeyler için ek kanıt çekimleri gerekir.';
  const guideLink=$('#guide-dialog > a');guideLink.href='../index.html#dashboard';guideLink.innerHTML=`ERP'ye dön ${icon('arrow')}`;
}
function toast(text){$('#real-toast').textContent=text;$('#real-toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#real-toast').classList.remove('visible'),4000);}
const badges={painted:'Boyalı',replaced:'Değişen',repair:'Onarım izli',local:'Lokal boyalı',original:'Orijinal',unchecked:'İncelenmedi'};
function statusTag(status,compact=false){return `<span class="r-status ${compact?'compact':''}" style="--status:${STATUS[status].dot}"><i></i>${badges[status]}</span>`;}
function setFrame(n,{manual=true}={}){
  if(!ready)return;if(manual)stopPlay();frame=normalizeFrame(n);$('#spin-image').src=imagePath(frame);$('#spin-image').alt=`Opel ADAM, ${directionForFrame(frame).toLocaleLowerCase('tr')}, gerçek fotoğraf ${frame}/24`;
  $('#frame-slider').value=frame;$('#frame-current').textContent=String(frame).padStart(2,'0');$('#frame-angle').textContent=angleForFrame(frame)+'°';$('#frame-direction').textContent=directionForFrame(frame);
  document.querySelectorAll('[data-frame]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.frame)===frame);b.setAttribute('aria-pressed',Number(b.dataset.frame)===frame);});renderPins();
}
function fitPhoto(){
  const stage=$('#spin-stage'),plane=$('#image-plane');const width=Math.min(stage.clientWidth-24,(stage.clientHeight-45)*1072/586);plane.style.width=width+'px';plane.style.height=width*586/1072+'px';plane.style.transform=`translate(-50%,-50%) scale(${zoom})`;
}
function selectPart(id,{jump=true}={}){selected=id;if(jump){setZoom(1);setFrame(BEST_FRAME[id]);}renderDetail();renderPins();renderParts();}
function renderPins(){
  const positions=anchorsAt(frame);$('#image-pins').innerHTML=showPins?Object.entries(positions).filter(([id])=>id===selected||findings[id]?.status!=='unchecked').map(([id,[x,y]])=>{const part=REAL_PARTS.find(p=>p.id===id);if(!part)return '';const active=id===selected;return `<button class="r-hotspot ${active?'active':''}" data-pin="${id}" style="left:${x}%;top:${y}%;--status:${STATUS[findings[id].status].dot}" aria-label="${esc(part.name)}: örnek ${esc(STATUS[findings[id].status].label)}"><span>${active?icon('plus'):''}</span><em>${part.name}</em></button>`;}).join(''):'';
  $('#image-pins').querySelectorAll('[data-pin]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();selectPart(b.dataset.pin,{jump:false});}));
}
function renderDetail(){
  const part=REAL_PARTS.find(p=>p.id===selected),f=findings[selected],values=f.measurements.split(', ').filter(Boolean),hasScenario=f.status!=='unchecked';
  $('#r-detail').innerHTML=`<div class="r-detail-heading"><span class="r-detail-index">${String(REAL_PARTS.indexOf(part)+1).padStart(2,'0')}<i>/ 23 PARÇA</i></span><h2>${part.name}</h2><div>${statusTag(f.status)}<span>${hasScenario?'Örnek değerlendirme':'Değerlendirme girilmedi'}</span></div></div><div class="r-detail-meta"><span>${part.material==='metal'?'Metal yüzey':part.material==='glass'?'Cam yüzey':'Plastik / kompozit'}</span><span>Fotoğrafla eşleştirildi</span></div><section class="r-note"><h3>Uzman bu parçayı nasıl anlatır?</h3><p>${esc(f.note||'Bu parça için henüz örnek değerlendirme girilmedi. Gerçek kontrol yapılmadan orijinal, boyalı veya değişen sonucu verilmez.')}</p></section>${selected==='roof'?'<div class="r-surface-warning">Tavanın üst yüzeyi bu çevre setinde tam görünmüyor. Ayrı üst açı ve yakın plan fotoğrafları gerekir.</div>':''}<div class="r-measure-label"><span>BOYA KALINLIĞI</span><b>ÖRNEK VERİ</b></div><div class="r-measures">${values.length?values.map((v,i)=>`<div><span>Nokta ${i+1}</span><strong>${esc(v)}<small>µm</small></strong></div>`).join(''):`<p>${part.material==='metal'?'Bu parça için ölçüm girilmedi.':'Bu yüzeyde standart Fe/NFe boya ölçümü kullanılmaz.'}</p>`}</div><button id="part-photo" class="r-detail-photo"><img src="${imagePath(BEST_FRAME[selected])}" alt="${part.name} için referans fotoğraf"/><span><strong>Parçanın bulunduğu kare</strong><small>${String(BEST_FRAME[selected]).padStart(2,'0')} / 24 · ${directionForFrame(BEST_FRAME[selected])}</small><em>Gerçek fotoğraf; hasar kanıtı değildir</em></span>${icon('arrow')}</button><button id="edit-real-finding" class="r-edit-button">${icon('edit')} Örnek notu düzenle</button>`;
  $('#part-photo').addEventListener('click',()=>{setFrame(BEST_FRAME[selected]);$('#spin-stage').focus({preventScroll:true});});
  $('#edit-real-finding').addEventListener('click',()=>{stopPlay();$('#real-edit-name').textContent=part.name;$('#real-edit-status').value=f.status;$('#real-edit-measure').value=f.measurements;$('#real-edit-note').value=f.note;$('#real-measure-field').hidden=part.material!=='metal';$('#real-edit-error').textContent='';$('#real-edit').showModal();});
  const examples=REAL_PARTS.filter(p=>findings[p.id].status!=='unchecked');$('#scenario-count').textContent=examples.length;
  $('#scenario-list').innerHTML=examples.map((p,i)=>`<button class="r-scenario ${p.id===selected?'active':''}" data-scenario="${p.id}"><span style="--status:${STATUS[findings[p.id].status].dot}">${String(i+1).padStart(2,'0')}</span><div><strong>${p.name}</strong><small>${STATUS[findings[p.id].status].label} · örnek senaryo</small></div>${icon('right')}</button>`).join('')||'<p class="r-empty">Henüz örnek bulgu yok.</p>';
  $('#scenario-list').querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>selectPart(b.dataset.scenario)));
}
function renderParts(){
  const parts=REAL_PARTS.filter(p=>filter==='all'||(filter==='examples'?findings[p.id].status!=='unchecked':findings[p.id].status==='unchecked'));
  $('#real-parts').innerHTML=parts.map(p=>`<button class="r-part ${p.id===selected?'active':''}" data-real-part="${p.id}" aria-pressed="${p.id===selected}"><span>${p.name}</span>${statusTag(findings[p.id].status,true)}${icon('right')}</button>`).join('')||'<p class="r-empty">Bu görünümde parça bulunmuyor.</p>';
  $('#real-parts').querySelectorAll('[data-real-part]').forEach(b=>b.addEventListener('click',()=>{selectPart(b.dataset.realPart);$('#spin-viewer').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}));
}
function stopPlay(){clearInterval(timer);timer=null;playing=false;$('#play-spin').innerHTML=icon('play');$('#play-spin').setAttribute('aria-pressed','false');$('#play-spin').setAttribute('aria-label','Otomatik döndür');}
function startPlay(){if(!ready)return;playing=true;$('#play-spin').innerHTML=icon('pause');$('#play-spin').setAttribute('aria-pressed','true');$('#play-spin').setAttribute('aria-label','Döndürmeyi durdur');timer=setInterval(()=>setFrame(frame+1,{manual:false}),180);}
$('#play-spin').addEventListener('click',()=>playing?stopPlay():startPlay());$('#previous-frame').addEventListener('click',()=>setFrame(frame-1));$('#next-frame').addEventListener('click',()=>setFrame(frame+1));$('#frame-slider').addEventListener('input',e=>setFrame(+e.target.value));
const stage=$('#spin-stage');
stage.addEventListener('pointerdown',e=>{if(!ready||e.target.closest('button'))return;stopPlay();drag={x:e.clientX,frame};stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');});
stage.addEventListener('pointermove',e=>{if(!drag)return;const step=Math.max(9,stage.clientWidth/48);setFrame(drag.frame-Math.round((e.clientX-drag.x)/step),{manual:false});});
for(const event of ['pointerup','pointercancel','lostpointercapture'])stage.addEventListener(event,()=>{drag=null;stage.classList.remove('dragging');});
stage.addEventListener('keydown',e=>{if(e.target!==stage)return;if(['ArrowLeft','ArrowRight','Home'].includes(e.key)){e.preventDefault();setFrame(e.key==='Home'?1:frame+(e.key==='ArrowRight'?1:-1));}});
$('#pins-toggle').addEventListener('click',()=>{showPins=!showPins;$('#pins-toggle').setAttribute('aria-pressed',showPins);renderPins();});
function setZoom(value){zoom=Math.max(1,Math.min(1.8,value));$('#zoom-label').textContent=zoom.toFixed(1)+'×';fitPhoto();$('#zoom-out-real').disabled=zoom===1;$('#zoom-in-real').disabled=zoom===1.8;}
$('#zoom-in-real').addEventListener('click',()=>setZoom(+(zoom+.2).toFixed(1)));$('#zoom-out-real').addEventListener('click',()=>setZoom(+(zoom-.2).toFixed(1)));
$('#expand-real').addEventListener('click',()=>{const expanded=document.body.classList.toggle('expanded-view');$('#expand-real').setAttribute('aria-pressed',expanded);requestAnimationFrame(fitPhoto);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('expanded-view')){$('#expand-real').click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopPlay();});
$('#r-thumbnails').innerHTML=[1,4,7,10,13,16,19,22].map(n=>`<button class="r-thumb ${n===frame?'selected':''}" data-frame="${n}" aria-pressed="${n===frame}"><img src="${imagePath(n)}" alt="${directionForFrame(n)}"/><span>${directionForFrame(n).replace(' görünüm','')}</span><small>${String(n).padStart(2,'0')} / 24</small></button>`).join('');
document.querySelectorAll('.r-thumb').forEach(b=>b.addEventListener('click',()=>setFrame(+b.dataset.frame)));
$('#all-photos').addEventListener('click',()=>{stopPlay();$('#gallery-grid').innerHTML=Array.from({length:24},(_,i)=>i+1).map(n=>`<button data-gallery-frame="${n}"><img src="${imagePath(n)}" alt="Opel ADAM gerçek kare ${n}"/><span><strong>${String(n).padStart(2,'0')}</strong>${directionForFrame(n)}<small>${angleForFrame(n)}°</small></span></button>`).join('');$('#gallery-grid').querySelectorAll('[data-gallery-frame]').forEach(b=>b.addEventListener('click',()=>{setFrame(+b.dataset.galleryFrame);$('#gallery-dialog').close();$('#spin-viewer').scrollIntoView({behavior:'smooth',block:'start'});}));$('#gallery-dialog').showModal();});
$('#open-guide').addEventListener('click',()=>{stopPlay();$('#guide-dialog').showModal();});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));
$('#real-filter').addEventListener('change',e=>{filter=e.target.value;renderParts();});
$('#real-edit-form').addEventListener('submit',e=>{e.preventDefault();try{const next=validateFinding(selected,{status:$('#real-edit-status').value,measurements:$('#real-measure-field').hidden?'':$('#real-edit-measure').value,note:$('#real-edit-note').value});findings[selected]=next;try{localStorage.setItem(sessionKey,JSON.stringify(findings));toast('Örnek senaryo bu tarayıcıda kaydedildi.');}catch{toast('Tarayıcıya kaydedilemedi; not bu oturumda görüntüleniyor.');}$('#real-edit').close();renderDetail();renderParts();renderPins();}catch(err){$('#real-edit-error').textContent=err.message;}});
$('#export-real').addEventListener('click',()=>{const data={schemaVersion:'ototr.real-spin-demo.v1',vehicle:'Opel ADAM',photoType:'real-photographic-sequence',frameCount:24,geometryReconstructed:false,inspectionDataIsFictional:true,commercialPhotoLicenseVerified:false,sourcePage:'https://www.webrotate360.com/examples/browse-all-examples/360-car-photography.aspx',parts:REAL_PARTS.map(p=>({...p,...findings[p.id],referenceFrame:BEST_FRAME[p.id]}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ototr-gercek-fotograf-ornek-senaryo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
new ResizeObserver(fitPhoto).observe(stage);fitPhoto();setZoom(1);renderDetail();renderParts();renderPins();
let loaded=0;
const loadImage=n=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{loaded++;$('#frame-loaded').textContent=`${loaded} / 24 kare hazır`;resolve(img);};img.onerror=()=>reject(new Error(`Kare ${n} yüklenemedi`));img.src=imagePath(n);});
try{await Promise.all(Array.from({length:24},(_,i)=>loadImage(i+1)));ready=true;$('#frame-loaded').innerHTML=`${icon('check')} 24 / 24 hazır`;for(const id of ['previous-frame','play-spin','next-frame','frame-slider'])$('#'+id).disabled=false;setFrame(frame);}catch(err){$('#frame-loaded').textContent='Fotoğraf yükleme hatası';toast(err.message+'; sayfayı yenileyin.');}
