const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright'),sharp=require('sharp');
const app=path.resolve(__dirname,'..'),out=path.join(app,'.local/pilot-qa');fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.json':'application/json','.ttf':'font/ttf'};
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]),file=path.resolve(app,'dist-erp','.'+(rel==='/'?'/pilot.html':rel));if(!file.startsWith(path.resolve(app,'dist-erp')+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(4320,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const tech='11111111-1111-4111-8111-111111111111',sid='22222222-2222-4222-8222-222222222222',cid='33333333-3333-4333-8333-333333333333';
 let session={id:sid,case_id:cid,profile:'hatchback3',status:'draft',revision:1,findings:{},photo_slots:{},editors:[tech],return_note:''};let photos=[],failedUpload=true,recorded=[],loginRequests=0,shareClosed=false,checked=0;
 const job={id:cid,session_id:sid,work_order_no:'QA-360 · Test kaydı',plate:'TEST 360',brand:'Opel',model:'ADAM · Test',owner_user_id:tech,is_locked:false,status:'TECHNICAL_ENTRY_OPEN'};
 const bundle=()=>({session,job,photos,can_write:session.status==='draft',can_review:false,issues:[]});
 await context.route('https://bsjkohwbtrfwrqcyhsfz.supabase.co/**',async route=>{const request=route.request(),url=new URL(request.url()),body=request.headers()['content-type']?.includes('application/json')?request.postDataJSON():null;const json=x=>route.fulfill({json:x});
  if(url.pathname==='/auth/v1/user')return json({id:tech});
  if(url.pathname==='/auth/v1/token'){loginRequests++;return json({access_token:'test-session-only',refresh_token:'test-refresh',expires_in:3600});}
  if(url.pathname.endsWith('/k360_identity'))return json({id:tech,name:'Pilot test personeli',role:'INSPECTION_TECHNICIAN'});
  if(url.pathname.endsWith('/k360_jobs'))return json([job]);
  if(url.pathname.endsWith('/kaporta-360-report'))return shareClosed?route.fulfill({status:404,json:{message:'Paylaşım bulunamadı veya süresi doldu.'}}):json({session:{...session,status:'approved'},job,photos:photos.map(p=>({...p,url:'http://127.0.0.1:4320/real-car/frame-01.jpg'})),approvedBy:'Test teknik sorumlusu',approvedAt:new Date().toISOString(),customerView:true});
  if(url.pathname.endsWith('/k360_load')||url.pathname.endsWith('/k360_open'))return json(bundle());
  if(url.pathname.endsWith('/k360_command')){recorded.push(body);if(body.expected_revision!==session.revision)return route.fulfill({status:409,json:{message:'Kayıt başka bir oturumda değişti. Yenileyip tekrar deneyin.'}});if(body.action==='finding')session.findings[body.payload.partId]=body.payload.finding;if(body.action==='photo'){photos.push({...body.payload,kind:body.payload.slot.startsWith('detail')?'detail':'ring'});session.photo_slots[body.payload.slot]=body.payload.id;}session.revision++;return json(bundle());}
  if(url.pathname.includes('/storage/v1/object/authenticated/'))return route.fulfill({path:path.join(app,'public/real-car/frame-01.jpg'),contentType:'image/jpeg'});
  if(url.pathname.includes('/storage/v1/object/kaporta-360/'))return failedUpload?route.abort('internetdisconnected'):json({Key:'test'});
  return route.fulfill({status:404,json:{message:'Unexpected test request'}});
 });
 const check=(name)=>{checked++;console.log('PASS '+name);};
 try{
  await page.goto('http://127.0.0.1:4320/pilot.html');await page.getByRole('heading',{name:'Ekspertize devam edin'}).waitFor();await page.screenshot({path:path.join(out,'01-login-desktop.png'),fullPage:true});check('ERP login, no fake automatic session');
  await page.getByLabel('E-posta',{exact:true}).fill('test@example.invalid');await page.getByLabel('Şifre',{exact:true}).fill('test-only');await page.getByRole('button',{name:'İş emirlerimi aç'}).click();await page.getByRole('heading',{name:'Kaporta incelemeleri'}).waitFor();assert.equal(loginRequests,1);
  await page.getByRole('button',{name:'İncelemeyi aç'}).click();await page.getByRole('heading',{name:'Çekim planı'}).waitFor();assert.equal(await page.locator('.shot').count(),28);check('Assigned work order, 28 explicit capture slots');
  const fixture=await sharp({create:{width:1280,height:960,channels:3,background:'#517956'}}).jpeg().toBuffer();
  await page.getByRole('button',{name:'Fotoğraf çek / seç'}).click();await page.locator('#camera-input').setInputFiles({name:'fixture.jpg',mimeType:'image/jpeg',buffer:fixture});await page.getByText('1 fotoğraf yükleme bekliyor',{exact:true}).waitFor();await page.waitForFunction(()=>!document.body.classList.contains('busy'));assert.equal(photos.length,0);check('Failed upload remains pending, never counted complete');
  await page.reload();await page.getByRole('button',{name:'İncelemeyi aç'}).click();await page.getByText('1 fotoğraf yükleme bekliyor',{exact:true}).waitFor();failedUpload=false;await page.getByRole('button',{name:'Yüklemeyi tekrar dene'}).click();await page.getByText('✓ Asıl fotoğraf kayıtlı',{exact:true}).waitFor();assert.equal(photos.length,1);check('Durable queue survives reload and retry registers original');
  await page.getByRole('button',{name:'02 · Parçalar'}).click();assert.equal(await page.locator('.part-list button').count(),23);await page.getByLabel('İnceleme durumu',{exact:true}).selectOption('inspected');await page.getByLabel('İşlem durumu',{exact:true}).selectOption('painted');await page.getByLabel('Boya ölçümleri').fill('211, 228, 215');await page.getByLabel('Çizik',{exact:true}).check();await page.getByLabel('Bulgu / kapsam açıklaması').fill('<script>alert(1)</script> Kaput ön kenarında test çizik.');await page.getByRole('button',{name:'Parça kaydını kaydet'}).click();await page.getByText('Parça kaydı sunucuya kaydedildi.',{exact:true}).waitFor();assert.equal(session.findings.hood.process,'painted');assert.deepEqual(session.findings.hood.defects,['scratch']);check('Process and defect are separate, Turkish measurements saved, note escaped');
  await page.getByRole('button',{name:'03 · Teknik inceleme'}).click();assert.equal(await page.getByRole('button',{name:'Teknik incelemeye gönder'}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Kaporta incelemesini onayla'}).isDisabled(),true);check('Incomplete report cannot submit and technician cannot approve');
  await page.getByRole('button',{name:'02 · Parçalar'}).click();await page.getByRole('button',{name:'Yakın plan ekle'}).click();const detail=await sharp({create:{width:1280,height:960,channels:3,background:'#a9bdb1'}}).jpeg().toBuffer();await page.locator('#camera-input').setInputFiles({name:'detail.jpg',mimeType:'image/jpeg',buffer:detail});await page.waitForFunction(()=>!document.body.classList.contains('busy'));await page.locator('[name=evidence]').last().check();await page.getByRole('button',{name:'Büyüt / işaretle'}).last().click();const area=page.locator('#annotation.editable');await area.waitFor();await page.waitForFunction(()=>document.querySelector('#annotation img')?.naturalWidth>0);const box=await area.boundingBox();await page.mouse.move(box.x+box.width*.2,box.y+box.height*.2);await page.mouse.down();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.up();await page.getByRole('button',{name:'Parça kaydını kaydet'}).click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));assert.equal(session.findings.hood.annotations.length,1);check('Detail evidence and normalized rectangle attached without changing original');
  const id=photos[0].id;for(let i=1;i<=24;i++){const pid=crypto.randomUUID(),slot='ring-'+String(i).padStart(2,'0');session.photo_slots[slot]=pid;photos.push({id:pid,slot,kind:'ring',path:'fixture/'+pid+'.jpg',sha256:String(i).padStart(64,'0')});}
  await page.getByRole('button',{name:'04 · Müşteri görünümü'}).click();await page.getByRole('button',{name:'Kaydı yenile',exact:true}).click();await page.locator('#spin-range').fill('6');await page.waitForFunction(()=>document.querySelector('#spin-stage img')?.naturalWidth>0);await page.screenshot({path:path.join(out,'02-customer-preview-desktop.png'),fullPage:true});assert.equal(await page.getByRole('button',{name:'Müşteri bağlantısı oluştur'}).isDisabled(),true);check('Photographic spin, evidence preview and final share gate');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'03-preview-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.getByRole('button',{name:'01 · Çekim'}).click();await page.screenshot({path:path.join(out,'04-capture-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);check('390px capture and customer preview without horizontal overflow');
  session.status='review';await page.getByRole('button',{name:'Kaydı yenile',exact:true}).click();await page.getByRole('button',{name:'02 · Parçalar'}).click();assert.equal(await page.getByLabel('İnceleme durumu',{exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Büyüt / işaretle'}).last().isDisabled(),false);await page.getByRole('button',{name:'Büyüt / işaretle'}).last().click();const popupReady=page.waitForEvent('popup');await page.getByRole('button',{name:'Asıl fotoğrafı aç'}).click();const original=await popupReady;await original.waitForURL('blob:**');await original.close();check('Read-only review prevents edits while retaining original-photo access');
  await page.getByRole('button',{name:'Çıkış',exact:true}).click();await page.getByRole('heading',{name:'Ekspertize devam edin'}).waitFor();await page.reload();await page.getByRole('heading',{name:'Ekspertize devam edin'}).waitFor();assert.equal(await page.evaluate(()=>sessionStorage.getItem('ototr-kaporta-auth-v1')),null);check('Logout clears pilot session and does not silently sign back in');
  await page.goto('http://127.0.0.1:4320/pilot.html#rapor='+'a'.repeat(64));await page.getByRole('heading',{name:'Aracınızı yakından tanıyın.'}).waitFor();assert.equal(await page.locator('#finding-form,#login-form,[data-action=logout],[data-action=share]').count(),0);await page.getByRole('button',{name:'Motor kaputu Boyalı'}).click();await page.locator('#spin-range').fill('4');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);check('Customer capability view has no staff/edit/share controls');shareClosed=true;await page.reload();await page.getByText('Paylaşım bulunamadı veya süresi doldu.',{exact:true}).waitFor();assert.equal(await page.locator('#spin-stage').count(),0);check('Revoked customer link shows no report');
  assert.deepEqual(errors,[]);check('No browser runtime errors');fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({passed:checked,errors,originalUploads:photos.length,commands:recorded.length},null,2));
 }catch(e){console.error("UI diagnostic:",(await page.locator("body").innerText()).slice(0,1600));throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
