import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';
const source=await readFile(new URL('../../../../supabase/functions/kaporta-360-report/index.ts',import.meta.url),'utf8');
const {createHandler}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
test('Customer edge: token authentication, allowed origin, snapshot-only signing and sanitized output',async()=>{
 const calls=[],handler=createHandler(k=>k==='SUPABASE_URL'?'https://example.supabase.co':'server-only',async(url,opts)=>{calls.push({url,body:JSON.parse(opts.body)});if(url.includes('/rest/'))return Response.json({session:{id:'hidden-session',editors:['private-user'],profile:'sedan4',findings:{hood:{evidenceIds:['detail']}},photo_slots:{'ring-01':'frame'}},job:{id:'internal-id',plate:'TEST',work_order_no:'TEST-01',brand:'Test',model:'Fixture'},photos:[{id:'frame',slot:'ring-01',kind:'ring',path:'session/frame.jpg'},{id:'detail',slot:'detail-1',kind:'detail',path:'session/detail.jpg'},{id:'old',path:'session/old.jpg'}],approvedBy:'Reviewer',approvedAt:new Date().toISOString()});return Response.json([{path:'session/frame.jpg',signedURL:'/object/sign/kaporta-360/session/frame.jpg?token=abc'},{path:'session/detail.jpg',signedURL:'/object/sign/kaporta-360/session/detail.jpg?token=def'}]);});
 const req=(body,origin='https://samivolkan.github.io')=>new Request('https://example.supabase.co/functions/v1/kaporta-360-report',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
 assert.equal((await handler(req({token:'bad'}))).status,404);assert.equal(calls.length,0);
 assert.equal((await handler(req({token:'a'.repeat(64)},'https://untrusted.example'))).status,403);
 const response=await handler(req({token:'a'.repeat(64)}));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const report=await response.json();assert.equal(report.photos.length,2);assert.equal(report.session.id,undefined);assert.equal(report.job.id,undefined);assert.equal(report.photos[0].path,undefined);assert.match(report.photos[0].url,/https:\/\/example.supabase.co\/storage\/v1\/object\/sign/);assert.equal(calls[1].body.expiresIn,120);assert.deepEqual(calls[1].body.paths,['session/frame.jpg','session/detail.jpg']);assert.ok(!JSON.stringify(report).includes('server-only'));
 const closed=createHandler(()=> 'configured',async()=>new Response('{}',{status:403}));assert.equal((await closed(req({token:'a'.repeat(64)}))).status,404);
});
