import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {randomUUID,createHash} from 'node:crypto';
import {SHOTS,partsFor,emptyFinding} from '../src/pilot-domain.js';
test('Kaporta PostgreSQL: ownership, immutable evidence, review, RLS and customer gates',async()=>{
 const db=new PGlite({extensions:{pgcrypto}});
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth; create schema storage; create schema extensions; create extension pgcrypto with schema extensions;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table app_users(id uuid primary key,auth_user_id uuid,branch_id uuid,full_name text,role text,is_active boolean);
 create table vehicles(id uuid primary key,plate text,brand text,model text,body_type text);
 create table expertise_cases(id uuid primary key,branch_id uuid,vehicle_id uuid references vehicles,work_order_no text,is_locked boolean default false,status text default 'TECHNICAL_ENTRY_OPEN',assigned_technician_id uuid,opened_at timestamptz default now(),revision_no int default 1,report_approved_at timestamptz);
 create table inspection_tasks(id uuid primary key,expertise_case_id uuid references expertise_cases,task_key text,owner_user_id uuid,assigned_user_id uuid,status text);
 create table final_reports(id uuid primary key,expertise_case_id uuid references expertise_cases,status text,locked_at timestamptz,revision_no int);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage,extensions to anon,authenticated,service_role;
 grant all on storage.objects to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;
 -- Deliberately permissive preexisting policy: the new bucket must still be protected.
 create policy legacy_storage on storage.objects for all to authenticated,anon using(true) with check(true);`);
 await db.exec(await readFile(new URL('../../../../supabase/migrations/20260906101627_kaporta_360_pilot.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../../../supabase/migrations/20260906110018_kaporta_360_technician_write_guard.sql',import.meta.url),'utf8'));
 const branch=randomUUID(),otherBranch=randomUUID(),tech=randomUUID(),supervisor=randomUUID(),foreign=randomUUID(),backup=randomUUID();
 const cid=randomUUID(),vehicle=randomUUID(),task=randomUUID();
 for(const [id,b,role] of [[tech,branch,'INSPECTION_TECHNICIAN'],[backup,branch,'INSPECTION_TECHNICIAN'],[supervisor,branch,'TECHNICAL_SUPERVISOR'],[foreign,otherBranch,'TECHNICAL_SUPERVISOR']])await db.query('insert into app_users values($1,$1,$2,$3,$4,true)',[id,b,'Test actor',role]);
 await db.query("insert into vehicles values($1,'TEST 360','Test','Fixture','hatchback')",[vehicle]);
 await db.query('insert into expertise_cases(id,branch_id,vehicle_id,work_order_no,assigned_technician_id) values($1,$2,$3,$4,$5)',[cid,branch,vehicle,'TEST-ONLY',tech]);
 await db.query("insert into inspection_tasks values($1,$2,'BODY_PAINT_CHECKUP',$3,$3,'OPEN')",[task,cid,tech]);
 const as=async(actor,fn,role='authenticated')=>{await db.query("select set_config('request.jwt.claim.sub',$1,false)",[actor||'']);await db.exec('set role '+role);try{return await fn();}finally{await db.exec('reset role');}};
 const rpc=async(name,args)=> (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
 let state=await as(tech,()=>rpc('k360_open',[cid,'hatchback3']));const sid=state.session.id;
 assert.equal(state.can_write,true);assert.equal(state.issues.length,51);
 await as(foreign,async()=>{await assert.rejects(rpc('k360_load',[sid]),/erişim/);assert.deepEqual((await db.query('select * from k360_sessions')).rows,[]);});
 await as(null,()=>assert.rejects(rpc('k360_jobs',[]),/permission denied/),'anon');
 await as(tech,()=>assert.rejects(db.query("update k360_sessions set status='approved'"),/permission denied/));
 const command=async(action,payload={},actor=tech,rev=state.session.revision)=>{const v=await as(actor,()=>rpc('k360_command',[sid,rev,action,JSON.stringify(payload)]));if(v.session)state=v;return v;};
 await assert.rejects(command('finding',{partId:'hood',finding:emptyFinding()},tech,0),/başka/);
 await assert.rejects(command('submit'),/Eksik/);
 await db.query("update expertise_cases set status='START_EVIDENCE_REQUIRED' where id=$1",[cid]);
 await assert.rejects(command('finding',{partId:'hood',finding:emptyFinding()}),/Yazma yetkisi/);
 await db.query("update expertise_cases set status='TECHNICAL_ENTRY_OPEN' where id=$1",[cid]);
 await assert.rejects(command('finding',{partId:'left_rear_door',finding:emptyFinding()}),/Geçersiz parça/);
 await assert.rejects(command('finding',{partId:'hood',finding:{...emptyFinding(),evidenceIds:[randomUUID()]}}),/ait değil/);
 await db.query('update inspection_tasks set owner_user_id=$1 where id=$2',[backup,task]);
 await assert.rejects(command('finding',{partId:'hood',finding:emptyFinding()}),/Yazma yetkisi/);
 await db.query('update inspection_tasks set owner_user_id=$1 where id=$2',[tech,task]);
 await db.query("update app_users set role='BRANCH_MANAGER' where id=$1",[tech]);
 await assert.rejects(command('finding',{partId:'hood',finding:emptyFinding()}),/Yazma yetkisi/);
 await db.query("update app_users set role='INSPECTION_TECHNICIAN' where id=$1",[tech]);
 for(const shot of SHOTS){
  const id=randomUUID(),path=`${sid}/${id}.jpg`,sha256=createHash('sha256').update(shot.id).digest('hex');
  const payload={id,slot:shot.id,path,sha256,mime:'image/jpeg',size:2000,width:1200,height:900,capturedAt:new Date().toISOString()};
  await assert.rejects(command('photo',payload),/aslı/);
  await as(tech,()=>db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['kaporta-360',path,JSON.stringify({size:2000,mimetype:'image/jpeg'})]));
  await command('photo',payload);
  if(shot.id==='ring-01'){
   assert.equal((await as(tech,()=>db.query('delete from storage.objects where name=$1 returning *',[path]))).rows.length,0);
   assert.equal((await as(foreign,()=>db.query('select * from storage.objects where name=$1',[path]))).rows.length,0);
   await as(foreign,()=>assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['kaporta-360',`${sid}/${randomUUID()}.jpg`]),/row-level/));
   await as(null,()=>assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['kaporta-360',`${sid}/${randomUUID()}.jpg`]),/row-level/),'anon');
   const before=state.session.revision;await command('photo',payload);assert.equal(state.session.revision,before);
  }
 }
 for(const p of partsFor('hatchback3'))await command('finding',{partId:p.id,finding:{...emptyFinding(),outcome:'inspected',process:'original',measurements:p.material==='metal'?[100,110,120]:[]}});
 await command('finding',{partId:'hood',finding:{...state.session.findings.hood,defects:['scratch'],note:'Test scratch evidence'}});
 await assert.rejects(command('submit'),/Eksik/);
 const detail=randomUUID(),path=`${sid}/${detail}.jpg`;
 await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['kaporta-360',path,JSON.stringify({size:2000,mimetype:'image/jpeg'})]);
 await command('photo',{id:detail,path,slot:'detail-'+detail,sha256:'d'.repeat(64),mime:'image/jpeg',size:2000,width:1200,height:900,capturedAt:new Date().toISOString()});
 await command('finding',{partId:'hood',finding:{...state.session.findings.hood,evidenceIds:[detail],annotations:[{photoId:detail,x:.1,y:.2,w:.1,h:.1}]}});
 await assert.rejects(command('finding',{partId:'hood',finding:{...state.session.findings.hood,annotations:[{photoId:detail,x:.9,y:0,w:.2,h:.1}]}}),/sınır/);
 assert.equal(state.issues.length,0);await command('submit');assert.equal(state.session.status,'review');
 await assert.rejects(command('finding',{partId:'hood',finding:emptyFinding()}),/Yazma yetkisi/);
 await db.query("update app_users set role='TECHNICAL_SUPERVISOR' where id=$1",[tech]);
 await assert.rejects(command('approve',{photosReviewed:true}),/hazırlamayan/);
 await assert.rejects(command('approve',{},supervisor),/Fotoğraf netliği/);
 await command('approve',{photosReviewed:true},supervisor);assert.equal(state.session.status,'approved');
 await assert.rejects(command('share',{},supervisor),/nihai rapor/);
 await db.query("update expertise_cases set is_locked=true,status='APPROVED',report_approved_at=now() where id=$1",[cid]);
 await assert.rejects(command('share',{},supervisor),/nihai rapor/);
 await db.query("insert into final_reports values($1,$2,'LOCKED',now(),1)",[randomUUID(),cid]);
 const share=await command('share',{},supervisor);assert.match(share.token,/^[a-f0-9]{64}$/);
 await as(null,()=>assert.rejects(rpc('k360_resolve_share',[share.token]),/permission denied/),'anon');
 let report=await as(null,()=>rpc('k360_resolve_share',[share.token]),'service_role');assert.equal(report.session.status,'approved');assert.equal(report.photos.length,29);
 await db.exec("update k360_shares set expires_at=now()-interval '1 second'");
 await as(null,()=>assert.rejects(rpc('k360_resolve_share',[share.token]),/bulunamadı/),'service_role');
 await db.exec("update k360_shares set expires_at=now()+interval '7 days'");
 await db.query('update expertise_cases set revision_no=2 where id=$1',[cid]);
 await as(null,()=>assert.rejects(rpc('k360_resolve_share',[share.token]),/bulunamadı/),'service_role');
 await db.query('update expertise_cases set revision_no=1 where id=$1',[cid]);
 await command('revoke',{},supervisor);
 await as(null,()=>assert.rejects(rpc('k360_resolve_share',[share.token]),/bulunamadı/),'service_role');
 await db.query("update expertise_cases set is_locked=false,status='TECHNICAL_ENTRY_OPEN' where id=$1",[cid]);
 await command('return',{note:'Yeni detay fotoğrafı gerekli'},supervisor);assert.equal(state.session.status,'returned');assert.equal(state.can_write,false);assert.equal((await as(tech,()=>rpc('k360_load',[sid]))).can_write,true);
 await db.query('update app_users set is_active=false where id=$1',[tech]);await as(tech,()=>assert.rejects(rpc('k360_load',[sid]),/erişim/));
 await db.close();
});
