import { LiveWorkOrder } from './types';

export const mockLiveOrders: LiveWorkOrder[] = [
  {
    id: 'IE-2026-000842',
    caseId: 'demo-case-842',
    workOrderNo: 'IE-2026-000842',
    status: 'IN_PROGRESS',
    openedAt: '2026-05-24T12:10:00.000Z',
    packageName: 'OTOTR Premium 360',
    durationMinutes: 145,
    customer: { name: 'Ahmet Can Yılmaz', phone: '0532 123 45 67', role: 'Müşteri' },
    vehicle: {
      plate: '34 OTR 360',
      vin: 'WBA***********694',
      brand: 'BMW',
      model: '320i M Sport',
      year: '2023',
      fuel: 'Benzin',
      transmission: 'Otomatik',
      mileage: '89.500 km',
    },
    gates: { managerApproved: false, secretaryReady: true, paymentReady: true, kvkkReady: true },
    evidence: [
      { id: 'F-001', caseId: 'demo-case-842', taskId: 'task-body', title: 'Ön genel görünüm', url: '', required: true, qualityStatus: 'OK' },
      { id: 'F-002', caseId: 'demo-case-842', taskId: 'task-obd', title: 'OBD ekranı', url: '', required: true, qualityStatus: 'OK' },
      { id: 'F-003', caseId: 'demo-case-842', taskId: 'task-brake', title: 'Fren test cihazı', url: '', required: true, qualityStatus: 'WAITING' },
    ],
    tasks: [
      {
        id: 'task-acceptance',
        caseId: 'demo-case-842',
        key: 'acceptance',
        title: 'Araç Kabul ve Rıza',
        role: 'Sekreterya',
        status: 'COMPLETED',
        reportFieldKey: 'work_orders.parties_and_consents',
        estimatedMinutes: 12,
        customerNote: 'KVKK, yol testi ve ödeme kapıları tamamlandı.',
        riskyFindings: '',
        evidenceCount: 1,
      },
      {
        id: 'task-body',
        caseId: 'demo-case-842',
        key: 'body_paint',
        title: 'Kaporta / Boya 59 Nokta',
        role: 'Kaporta Ustası',
        status: 'IN_PROGRESS',
        reportFieldKey: 'task_results.body_paint',
        estimatedMinutes: 35,
        customerNote: 'Sağ arka kapıda lokal boya ölçümü farklılık gösteriyor.',
        riskyFindings: 'Fotoğraf ve ikinci usta kontrolü gerekli.',
        evidenceCount: 1,
      },
      {
        id: 'task-engine',
        caseId: 'demo-case-842',
        key: 'engine_checkup',
        title: 'Motor Üst Mekanik',
        role: 'Mekanik Usta',
        status: 'COMPLETED',
        reportFieldKey: 'task_results.engine_checkup',
        estimatedMinutes: 30,
        customerNote: 'Motor üst bölgede aktif yağ kaçağı görülmedi.',
        riskyFindings: '',
        evidenceCount: 0,
      },
      {
        id: 'task-obd',
        caseId: 'demo-case-842',
        key: 'obd',
        title: 'OBD / Beyin Test',
        role: 'Diagnostik',
        status: 'WAITING',
        reportFieldKey: 'task_results.obd_modules',
        estimatedMinutes: 18,
        customerNote: 'Cihaz ekranı bekleniyor.',
        riskyFindings: '',
        evidenceCount: 1,
      },
      {
        id: 'task-brake',
        caseId: 'demo-case-842',
        key: 'brake_suspension',
        title: 'Fren / Süspansiyon',
        role: 'Test Operatörü',
        status: 'WAITING',
        reportFieldKey: 'task_results.test_station',
        estimatedMinutes: 22,
        customerNote: '',
        riskyFindings: '',
        evidenceCount: 1,
      },
    ],
  },
];
